### ISSUE TITLE
Create sdist of uwsgi for PyPI

### ISSUE THREAD

**Issue by mwicat** [unbit/uwsgi#1018]
I tried to package and upload patched uwsgi 2.0.11.1 to our internal PyPI server (devpi), yet I cannot get it to work. @unbit  can you share your procedure how you package and upload uwsgi to PyPI server? It seems that necessary files aren't added into sdist archive:

```bash
mwiewiorski@butapren:~/work/uwsgi$ git clone https://github.com/unbit/uwsgi
mwiewiorski@butapren:~/work/uwsgi$ git checkout 2.0.11.1
mwiewiorski@butapren:~/work/uwsgi$ python setup.py sdist
running sdist
running egg_info
writing uWSGI.egg-info/PKG-INFO
writing top-level names to uWSGI.egg-info/top_level.txt
writing dependency_links to uWSGI.egg-info/dependency_links.txt
reading manifest file 'uWSGI.egg-info/SOURCES.txt'
writing manifest file 'uWSGI.egg-info/SOURCES.txt'
running check
warning: check: missing required meta-data: url

creating uWSGI-2.0.11.1
creating uWSGI-2.0.11.1/uWSGI.egg-info
making hard links in uWSGI-2.0.11.1...
hard linking README -> uWSGI-2.0.11.1
hard linking setup.py -> uWSGI-2.0.11.1
hard linking uwsgidecorators.py -> uWSGI-2.0.11.1
hard linking uWSGI.egg-info/PKG-INFO -> uWSGI-2.0.11.1/uWSGI.egg-info
hard linking uWSGI.egg-info/SOURCES.txt -> uWSGI-2.0.11.1/uWSGI.egg-info
hard linking uWSGI.egg-info/dependency_links.txt -> uWSGI-2.0.11.1/uWSGI.egg-info
hard linking uWSGI.egg-info/top_level.txt -> uWSGI-2.0.11.1/uWSGI.egg-info
Writing uWSGI-2.0.11.1/setup.cfg
Creating tar archive
removing 'uWSGI-2.0.11.1' (and everything under it)
mwiewiorski@butapren:~/work/uwsgi$ tar tvf dist/uWSGI-2.0.11.1.tar.gz 
drwxrwxr-x mwiewiorski/mwiewiorski 0 2015-08-26 13:06 uWSGI-2.0.11.1/
-rw-rw-r-- mwiewiorski/mwiewiorski 10206 2015-08-26 12:28 uWSGI-2.0.11.1/uwsgidecorators.py
-rw-rw-r-- mwiewiorski/mwiewiorski   148 2015-08-26 12:28 uWSGI-2.0.11.1/README
-rw-rw-r-- mwiewiorski/mwiewiorski    59 2015-08-26 13:06 uWSGI-2.0.11.1/setup.cfg
-rw-rw-r-- mwiewiorski/mwiewiorski  2824 2015-08-26 12:28 uWSGI-2.0.11.1/setup.py
-rw-rw-r-- mwiewiorski/mwiewiorski   192 2015-08-26 13:06 uWSGI-2.0.11.1/PKG-INFO
drwxrwxr-x mwiewiorski/mwiewiorski     0 2015-08-26 13:06 uWSGI-2.0.11.1/uWSGI.egg-info/
-rw-rw-r-- mwiewiorski/mwiewiorski   150 2015-08-26 13:06 uWSGI-2.0.11.1/uWSGI.egg-info/SOURCES.txt
-rw-rw-r-- mwiewiorski/mwiewiorski    16 2015-08-26 13:06 uWSGI-2.0.11.1/uWSGI.egg-info/top_level.txt
-rw-rw-r-- mwiewiorski/mwiewiorski   192 2015-08-26 13:06 uWSGI-2.0.11.1/uWSGI.egg-info/PKG-INFO
-rw-rw-r-- mwiewiorski/mwiewiorski     1 2015-08-26 13:06 uWSGI-2.0.11.1/uWSGI.egg-info/dependency_links.txt

(...)
mwiewiorski@butapren:~/work/uwsgi$ sudo pip install --upgrade uwsgi==2.0.11.1
  Downloading http://repo/root/opera/+f/604/9b66075b32c0e/uWSGI-2.0.11.1.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-BHt_Ol/uwsgi/setup.py", line 3, in <module>
        import uwsgiconfig as uc
    ImportError: No module named uwsgiconfig
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-BHt_Ol/uwsgi/setup.py", line 3, in <module>
    
        import uwsgiconfig as uc
    
    ImportError: No module named uwsgiconfig
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BHt_Ol/uwsgi

```

**Comment by mwicat** [comment]
@unbit do you have any clues?

**Comment by unbit** [comment]
Hi, Unfortunately i directly upload tarballs to pypi servers. I do not have an automated tarball generation from setuptools

**Comment by mwicat** [comment]
@unbit OK, that explains a lot, I suspected that. ;) Thanks for your response!

**Comment by samriang** [comment]
I have same error when trying to build RPM with 'python setup.py bdist_rpm'.
Looking for any advice :/

**Comment by asottile** [comment]
This gets me close enough (it builds):

```
$ cat MANIFEST.in 
include uwsgiconfig.py
include buildconf/default.ini
include buildconf/base.ini
include *.h
include core/*.c
include lib/*.c
include proto/*.c
recursive-include plugins *.c
recursive-include plugins *.h
recursive-include plugins *.py
```
