### ISSUE TITLE
uwsgi.route segfaults with python3.4+

### ISSUE THREAD

**Issue by dakra** [unbit/uwsgi#1041]
I compiled uwsgi with python3.5 (I tried 3.4 as well) and every time I call
`uwsgi.route("uwsgi", "/tmp/foo,0,0")` from my app, uwsgi crashes.

```
 ./uwsgi --show-config --ini-paste-logged ~/atomx/api/uwsgi.ini 
[uWSGI] getting INI configuration from /home/daniel/atomx/api/uwsgi.ini

;uWSGI instance configuration
[uwsgi]
show-config = true
ini-paste-logged = /home/daniel/atomx/api/uwsgi.ini
http-socket = :6543
paste = config:/home/daniel/atomx/api/development.ini
paste-logger = /home/daniel/atomx/api/development.ini
enable-threads = true
virtualenv = /home/daniel/.virtualenvs/atomx35
offload-threads = 2
;end of configuration

*** Starting uWSGI 2.1-dev-59a76bb (64bit) on [Wed Sep 16 07:47:03 2015] ***
compiled with version: 5.2.0 on 16 September 2015 07:24:39
os: Linux-4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015
nodename: matrix
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/daniel/github/uwsgi
detected binary path: /home/daniel/github/uwsgi/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 62938
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :6543 fd 4
Python version: 3.5.0 (default, Sep 15 2015, 16:09:16)  [GCC 5.2.0]
Set PythonHome to /home/daniel/.virtualenvs/atomx35
Python main interpreter initialized at 0x55c5994935a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
your request buffer size is 4096 bytes
mapped 72792 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Loading paste environment: config:/home/daniel/atomx/api/development.ini
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55c5994935a0 pid: 14591 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 14591, cores: 1)
spawned 2 offload threads for uWSGI worker 1
!!! uWSGI process 14591 got Segmentation Fault !!!
*** backtrace of 14591 ***
./uwsgi(uwsgi_backtrace+0x40) [0x55c59724da10]
./uwsgi(uwsgi_segfault+0x3a) [0x55c59724de6a]
/usr/lib/libc.so.6(+0x33680) [0x7ff3fb186680]
./uwsgi(uwsgi_routing_translate+0x4b) [0x55c59725b58b]
./uwsgi(+0xd5640) [0x55c59728b640]
./uwsgi(uwsgi_route_api_func+0x75) [0x55c59725e3e5]
./uwsgi(+0xbf6ea) [0x55c5972756ea]
/usr/lib/libpython3.5m.so.1.0(PyCFunction_Call+0xd9) [0x7ff3fb7e51c9]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x86a7) [0x7ff3fb863947]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x849b) [0x7ff3fb86373b]
/usr/lib/libpython3.5m.so.1.0(+0x135ba8) [0x7ff3fb864ba8]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x68b2) [0x7ff3fb861b52]
/usr/lib/libpython3.5m.so.1.0(+0x135ba8) [0x7ff3fb864ba8]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x68b2) [0x7ff3fb861b52]
/usr/lib/libpython3.5m.so.1.0(+0x135ba8) [0x7ff3fb864ba8]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x68b2) [0x7ff3fb861b52]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x849b) [0x7ff3fb86373b]
/usr/lib/libpython3.5m.so.1.0(+0x135ba8) [0x7ff3fb864ba8]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x68b2) [0x7ff3fb861b52]
/usr/lib/libpython3.5m.so.1.0(+0x135ba8) [0x7ff3fb864ba8]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x68b2) [0x7ff3fb861b52]
/usr/lib/libpython3.5m.so.1.0(+0x135ba8) [0x7ff3fb864ba8]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x68b2) [0x7ff3fb861b52]
/usr/lib/libpython3.5m.so.1.0(+0x135ba8) [0x7ff3fb864ba8]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x68b2) [0x7ff3fb861b52]
/usr/lib/libpython3.5m.so.1.0(+0x135ba8) [0x7ff3fb864ba8]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x68b2) [0x7ff3fb861b52]
/usr/lib/libpython3.5m.so.1.0(+0x135ba8) [0x7ff3fb864ba8]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalCodeEx+0x31) [0x7ff3fb864ca1]
/usr/lib/libpython3.5m.so.1.0(+0x97a04) [0x7ff3fb7c6a04]
/usr/lib/libpython3.5m.so.1.0(PyObject_Call+0x7b) [0x7ff3fb79878b]
/usr/lib/libpython3.5m.so.1.0(+0x8263d) [0x7ff3fb7b163d]
/usr/lib/libpython3.5m.so.1.0(PyObject_Call+0x7b) [0x7ff3fb79878b]
/usr/lib/libpython3.5m.so.1.0(+0xcdd14) [0x7ff3fb7fcd14]
/usr/lib/libpython3.5m.so.1.0(PyObject_Call+0x7b) [0x7ff3fb79878b]
/usr/lib/libpython3.5m.so.1.0(PyEval_CallObjectWithKeywords+0x5b) [0x7ff3fb85af6b]
./uwsgi(python_call+0x29) [0x55c597268969]
./uwsgi(uwsgi_request_wsgi+0x122) [0x55c59726afb2]
./uwsgi(wsgi_req_recv+0xc1) [0x55c5971f47e1]
./uwsgi(simple_loop_run+0xd6) [0x55c597248ce6]
./uwsgi(uwsgi_ignition+0x260) [0x55c59724e190]
./uwsgi(uwsgi_worker_run+0x2a5) [0x55c5972530d5]
./uwsgi(uwsgi_run+0x427) [0x55c597253667]
./uwsgi(+0x3dc21) [0x55c5971f3c21]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7ff3fb173610]
./uwsgi(_start+0x29) [0x55c5971f3c59]
*** end of backtrace ***
```

Compiled with `-g` and in gdb:
```
$ gdb ./uwsgi
GNU gdb (GDB) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./uwsgi...done.
(gdb) run --ini-paste-logged /home/daniel/atomx/api/uwsgi.ini
Starting program: /home/daniel/github/uwsgi/uwsgi --ini-paste-logged /home/daniel/atomx/api/uwsgi.ini
/home/daniel/.virtualenvs/atomx35/bin/python: No module named virtualfish
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[uWSGI] getting INI configuration from /home/daniel/atomx/api/uwsgi.ini
*** Starting uWSGI 2.1-dev-59a76bb (64bit) on [Wed Sep 16 07:42:03 2015] ***
compiled with version: 5.2.0 on 16 September 2015 07:24:39
os: Linux-4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015
nodename: matrix
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/daniel/github/uwsgi
detected binary path: /home/daniel/github/uwsgi/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 62938
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :6543 fd 4
Python version: 3.5.0 (default, Sep 15 2015, 16:09:16)  [GCC 5.2.0]
Set PythonHome to /home/daniel/.virtualenvs/atomx35
Python main interpreter initialized at 0x5555558c16a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
your request buffer size is 4096 bytes
mapped 72792 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Loading paste environment: config:/home/daniel/atomx/api/development.ini
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5555558c16a0 pid: 1906 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 1906, cores: 1)
[New Thread 0x7fffedba6700 (LWP 2035)]
[New Thread 0x7fffedb25700 (LWP 2036)]
spawned 2 offload threads for uWSGI worker 1

Program received signal SIGSEGV, Segmentation fault.
0x00005555555f958b in uwsgi_routing_translate (wsgi_req=wsgi_req@entry=0x7ffff4acc078, ur=ur@entry=0x555556ef06a0, subject=0xc <error: Cannot access memory at address 0xc>, 
    subject_len=12, data=data@entry=0x555556c07cb4 "/tmp/foo", data_len=8) at core/routing.c:48
48		if (ur->condition_ub[wsgi_req->async_id] && ur->ovn[wsgi_req->async_id] > 0) {
(gdb) bt
#0  0x00005555555f958b in uwsgi_routing_translate (wsgi_req=wsgi_req@entry=0x7ffff4acc078, ur=ur@entry=0x555556ef06a0, 
    subject=0xc <error: Cannot access memory at address 0xc>, subject_len=12, data=data@entry=0x555556c07cb4 "/tmp/foo", data_len=8) at core/routing.c:48
#1  0x0000555555629640 in uwsgi_routing_func_uwsgi_remote (wsgi_req=0x7ffff4acc078, ur=0x555556ef06a0) at plugins/router_uwsgi/router_uwsgi.c:47
#2  0x00005555555fc3e5 in uwsgi_route_api_func (wsgi_req=wsgi_req@entry=0x7ffff4acc078, router=<optimized out>, args=0x555556c17f00 "/tmp/foo") at core/routing.c:545
#3  0x00005555556136ea in py_uwsgi_route (self=<optimized out>, args=0x7fffedc7f388) at plugins/python/uwsgi_pymodule.c:782
#4  0x00007ffff5ba01c9 in PyCFunction_Call (func=func@entry=0x7ffff4ad2d38, args=args@entry=0x7fffedc7f388, kwds=kwds@entry=0x0) at Objects/methodobject.c:109
#5  0x00007ffff5c1e947 in call_function (oparg=<optimized out>, pp_stack=0x7fffffffcd50) at Python/ceval.c:4651
#6  PyEval_EvalFrameEx (f=f@entry=0x5555569b4988, throwflag=throwflag@entry=0) at Python/ceval.c:3181
#7  0x00007ffff5c1e73b in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffffffce80, func=<optimized out>) at Python/ceval.c:4750
#8  call_function (oparg=<optimized out>, pp_stack=0x7fffffffce80) at Python/ceval.c:4677
#9  PyEval_EvalFrameEx (f=f@entry=0x7fffedbc07a8, throwflag=throwflag@entry=0) at Python/ceval.c:3181
#10 0x00007ffff5c1fba8 in _PyEval_EvalCodeWithName (_co=0x7ffff0ae0150, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=2, kws=0x5555569afce8, 
    kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x7fffedc80cc8, name=0x7ffff1cf0a30, qualname=0x7ffff0ada4e0) at Python/ceval.c:3962
#11 0x00007ffff5c1cb52 in fast_function (nk=<optimized out>, na=<optimized out>, n=2, pp_stack=0x7fffffffd090, func=<optimized out>) at Python/ceval.c:4760
#12 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd090) at Python/ceval.c:4677
#13 PyEval_EvalFrameEx (f=f@entry=0x5555569afaf8, throwflag=throwflag@entry=0) at Python/ceval.c:3181
#14 0x00007ffff5c1fba8 in _PyEval_EvalCodeWithName (_co=0x7ffff0add8a0, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=2, kws=0x555556bf9960, 
    kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x7fffedba72d0, name=0x7ffff1cf0a30, qualname=0x7ffff0b42a58) at Python/ceval.c:3962
#15 0x00007ffff5c1cb52 in fast_function (nk=<optimized out>, na=<optimized out>, n=2, pp_stack=0x7fffffffd2a0, func=<optimized out>) at Python/ceval.c:4760
#16 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd2a0) at Python/ceval.c:4677
#17 PyEval_EvalFrameEx (f=f@entry=0x555556bf9758, throwflag=throwflag@entry=0) at Python/ceval.c:3181
#18 0x00007ffff5c1fba8 in _PyEval_EvalCodeWithName (_co=0x7ffff13b9540, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=5, kws=0x5555569ac2f0, 
    kwcount=0, defs=0x7ffff13b8880, defcount=4, kwdefs=0x0, closure=0x0, name=0x7ffff13db370, qualname=0x7ffff13db370) at Python/ceval.c:3962
#19 0x00007ffff5c1cb52 in fast_function (nk=<optimized out>, na=<optimized out>, n=5, pp_stack=0x7fffffffd4b0, func=<optimized out>) at Python/ceval.c:4760
#20 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd4b0) at Python/ceval.c:4677
#21 PyEval_EvalFrameEx (f=f@entry=0x5555569ac078, throwflag=throwflag@entry=0) at Python/ceval.c:3181
#22 0x00007ffff5c1e73b in fast_function (nk=<optimized out>, na=<optimized out>, n=2, pp_stack=0x7fffffffd5e0, func=<optimized out>) at Python/ceval.c:4750
#23 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd5e0) at Python/ceval.c:4677
#24 PyEval_EvalFrameEx (f=f@entry=0x555556bca298, throwflag=throwflag@entry=0) at Python/ceval.c:3181
#25 0x00007ffff5c1fba8 in _PyEval_EvalCodeWithName (_co=0x7fffee7f30c0, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=1, kws=0x555556bcba50, 
    kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x7fffeee36888, name=0x7fffee7acf70, qualname=0x7fffee794348) at Python/ceval.c:3962
#26 0x00007ffff5c1cb52 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffffffd7f0, func=<optimized out>) at Python/ceval.c:4760
#27 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd7f0) at Python/ceval.c:4677
#28 PyEval_EvalFrameEx (f=f@entry=0x555556bcb888, throwflag=throwflag@entry=0) at Python/ceval.c:3181
#29 0x00007ffff5c1fba8 in _PyEval_EvalCodeWithName (_co=0x7ffff138c930, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=1, kws=0x555556bcdb68, 
    kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x7fffeea1b488, name=0x7ffff13b7df0, qualname=0x7ffff13ebab0) at Python/ceval.c:3962
#30 0x00007ffff5c1cb52 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffffffda00, func=<optimized out>) at Python/ceval.c:4760
#31 call_function (oparg=<optimized out>, pp_stack=0x7fffffffda00) at Python/ceval.c:4677
#32 PyEval_EvalFrameEx (f=f@entry=0x555556bcd9b8, throwflag=throwflag@entry=0) at Python/ceval.c:3181
#33 0x00007ffff5c1fba8 in _PyEval_EvalCodeWithName (_co=0x7fffef05b4b0, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=1, kws=0x5555569af740, 
    kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x7fffee7f7ac8, name=0x7fffef074228, qualname=0x7fffef51e930) at Python/ceval.c:3962
#34 0x00007ffff5c1cb52 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffffffdc10, func=<optimized out>) at Python/ceval.c:4760
#35 call_function (oparg=<optimized out>, pp_stack=0x7fffffffdc10) at Python/ceval.c:4677
#36 PyEval_EvalFrameEx (f=f@entry=0x5555569af498, throwflag=throwflag@entry=0) at Python/ceval.c:3181
#37 0x00007ffff5c1fba8 in _PyEval_EvalCodeWithName (_co=0x7fffef5c1d20, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=1, kws=0x555556bef4a8, 
    kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x7fffedc907c8, name=0x7fffef5381b0, qualname=0x7fffef539030) at Python/ceval.c:3962
#38 0x00007ffff5c1cb52 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffffffde20, func=<optimized out>) at Python/ceval.c:4760
#39 call_function (oparg=<optimized out>, pp_stack=0x7fffffffde20) at Python/ceval.c:4677
#40 PyEval_EvalFrameEx (f=f@entry=0x555556bef2c8, throwflag=throwflag@entry=0) at Python/ceval.c:3181
#41 0x00007ffff5c1fba8 in _PyEval_EvalCodeWithName (_co=0x7ffff1315540, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=2, kws=0x7fffedcca798, 
    kwcount=1, defs=0x7ffff13d4840, defcount=1, kwdefs=0x0, closure=0x0, name=0x7ffff13cb390, qualname=0x7ffff10043f0) at Python/ceval.c:3962
#42 0x00007ffff5c1cb52 in fast_function (nk=<optimized out>, na=<optimized out>, n=4, pp_stack=0x7fffffffe030, func=<optimized out>) at Python/ceval.c:4760
#43 call_function (oparg=<optimized out>, pp_stack=0x7fffffffe030) at Python/ceval.c:4677
#44 PyEval_EvalFrameEx (f=f@entry=0x7fffedcca5e8, throwflag=throwflag@entry=0) at Python/ceval.c:3181
#45 0x00007ffff5c1fba8 in _PyEval_EvalCodeWithName (_co=0x7ffff13158a0, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x7fffeea50570, argcount=3, 
    kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:3962
#46 0x00007ffff5c1fca1 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x7fffeea50570, argcount=<optimized out>, 
    kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:3983
#47 0x00007ffff5b81a04 in function_call (func=0x7ffff13ba730, arg=0x7fffeea50558, kw=0x0) at Objects/funcobject.c:632
#48 0x00007ffff5b5378b in PyObject_Call (func=0x7ffff13ba730, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2147
#49 0x00007ffff5b6c63d in method_call (func=0x7ffff13ba730, arg=0x7fffeea50558, kw=0x0) at Objects/classobject.c:330
#50 0x00007ffff5b5378b in PyObject_Call (func=0x7fffeea12cc8, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2147
#51 0x00007ffff5bb7d14 in slot_tp_call (self=<optimized out>, args=0x7ffff1d4d648, kwds=0x0) at Objects/typeobject.c:6053
#52 0x00007ffff5b5378b in PyObject_Call (func=0x7fffef41b7b8, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2147
#53 0x00007ffff5c15f6b in PyEval_CallObjectWithKeywords (func=0x7fffef41b7b8, arg=0x7ffff1d4d648, kw=kw@entry=0x0) at Python/ceval.c:4526
#54 0x0000555555606969 in python_call (callable=<optimized out>, args=<optimized out>, catch=0, wsgi_req=0x7ffff4acc078) at plugins/python/pyutils.c:264
#55 0x0000555555608fb2 in uwsgi_request_wsgi (wsgi_req=0x7ffff4acc078) at plugins/python/wsgi_handlers.c:403
#56 0x00005555555927e1 in wsgi_req_recv (queue=queue@entry=11, wsgi_req=wsgi_req@entry=0x7ffff4acc078) at core/utils.c:1442
#57 0x00005555555e6ce6 in simple_loop_run (arg1=0x0) at core/loop.c:144
#58 0x00005555555ec190 in uwsgi_ignition () at core/uwsgi.c:3651
#59 0x00005555555f10d5 in uwsgi_worker_run () at core/uwsgi.c:3579
#60 0x00005555555f1667 in uwsgi_run () at core/uwsgi.c:3489
#61 0x0000555555591c21 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at core/uwsgi.c:2064
(gdb) 
```

Everything else works fine.
The response-route-if approach from the tutorial works fine as well.
So if I do:
```
uwsgi.add_var("OFFLOAD_TO_WEBSOCKET", "y")
uwsgi.add_var("OFFLOAD_SERVER", "/tmp/foo")
```
and
```
response-route-if = equal:${OFFLOAD_TO_WEBSOCKET};y disableheaders:
response-route-if = equal:${OFFLOAD_TO_WEBSOCKET};y uwsgi:${OFFLOAD_SERVER},0,0
```
it works as expected.

**Comment by xrmx** [comment]
Thanks for reporting. Does the specific version of python in the title means that the same configuration works fine with python 2.7?

**Comment by dakra** [comment]
It just meant I only tested it with python3.4 and 3.5.
But I downloaded and tested it with python 2.7.10 as well, same bug:
```
$  uwsgi --show-config --ini-paste-logged uwsgi.ini 
[uWSGI] getting INI configuration from uwsgi.ini

;uWSGI instance configuration
[uwsgi]
show-config = true
ini-paste-logged = uwsgi.ini
http-socket = :6543
paste = config:/home/daniel/atomx/api/development.ini
paste-logger = /home/daniel/atomx/api/development.ini
enable-threads = true
virtualenv = /home/daniel/.virtualenvs/tesetpy2
offload-threads = 2
;end of configuration

*** Starting uWSGI 2.0.11.1 (64bit) on [Mon Oct  5 13:30:12 2015] ***
compiled with version: 5.2.0 on 05 October 2015 13:23:26
os: Linux-4.2.2-1-ARCH #1 SMP PREEMPT Tue Sep 29 22:21:33 CEST 2015
nodename: matrix
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/daniel/atomx/api
detected binary path: /home/daniel/.virtualenvs/tesetpy2/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 62938
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :6543 fd 4
Python version: 2.7.10 (default, Sep  7 2015, 13:51:49)  [GCC 5.2.0]
Set PythonHome to /home/daniel/.virtualenvs/tesetpy2
Python main interpreter initialized at 0x55bb04d61730
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Loading paste environment: config:/home/daniel/atomx/api/development.ini
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55bb04d61730 pid: 8288 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 8288, cores: 1)
spawned 2 offload threads for uWSGI worker 1
2015-10-05 13:30:22,120 INFO  [sqlalchemy.engine.base.Engine][uWSGIWorker1Core0] SHOW VARIABLES LIKE 'sql_mode'
2015-10-05 13:30:22,120 INFO  [sqlalchemy.engine.base.Engine][uWSGIWorker1Core0] {}
2015-10-05 13:30:22,121 INFO  [sqlalchemy.engine.base.Engine][uWSGIWorker1Core0] SELECT DATABASE()
2015-10-05 13:30:22,121 INFO  [sqlalchemy.engine.base.Engine][uWSGIWorker1Core0] {}
2015-10-05 13:30:22,122 INFO  [sqlalchemy.engine.base.Engine][uWSGIWorker1Core0] SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
2015-10-05 13:30:22,123 INFO  [sqlalchemy.engine.base.Engine][uWSGIWorker1Core0] {}
2015-10-05 13:30:22,123 INFO  [sqlalchemy.engine.base.Engine][uWSGIWorker1Core0] SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
2015-10-05 13:30:22,123 INFO  [sqlalchemy.engine.base.Engine][uWSGIWorker1Core0] {}
2015-10-05 13:30:22,124 INFO  [sqlalchemy.engine.base.Engine][uWSGIWorker1Core0] BEGIN (implicit)
2015-10-05 13:30:22,125 INFO  [sqlalchemy.engine.base.Engine][uWSGIWorker1Core0] SELECT users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.id AS users_id, users.state AS users_state, users.name AS users_name, users.email AS users_email, users.can_review AS users_can_review 
FROM users 
WHERE users.id = %(id_1)s
2015-10-05 13:30:22,125 INFO  [sqlalchemy.engine.base.Engine][uWSGIWorker1Core0] {u'id_1': 4}
!!! uWSGI process 8288 got Segmentation Fault !!!
*** backtrace of 8288 ***
uwsgi(uwsgi_backtrace+0x40) [0x55bb040e1950]
uwsgi(uwsgi_segfault+0x3a) [0x55bb040e1d4a]
/usr/lib/libc.so.6(+0x33680) [0x7f4945c73680]
uwsgi(uwsgi_routing_translate+0x4b) [0x55bb040eeedb]
uwsgi(+0xcf408) [0x55bb0411e408]
uwsgi(uwsgi_route_api_func+0x75) [0x55bb040f1d25]
uwsgi(+0xb9a2a) [0x55bb04108a2a]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x53cc) [0x7f494630864c]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5ae1) [0x7f4946308d61]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x853) [0x7f4946309f03]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5a2c) [0x7f4946308cac]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x853) [0x7f4946309f03]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5a2c) [0x7f4946308cac]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x853) [0x7f4946309f03]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5a2c) [0x7f4946308cac]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5ae1) [0x7f4946308d61]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x853) [0x7f4946309f03]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5a2c) [0x7f4946308cac]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x853) [0x7f4946309f03]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5a2c) [0x7f4946308cac]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x853) [0x7f4946309f03]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5a2c) [0x7f4946308cac]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x853) [0x7f4946309f03]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5a2c) [0x7f4946308cac]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x853) [0x7f4946309f03]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5a2c) [0x7f4946308cac]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x853) [0x7f4946309f03]
/usr/lib/libpython2.7.so.1.0(+0x72d48) [0x7f494628ed48]
/usr/lib/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f4946267657]
/usr/lib/libpython2.7.so.1.0(+0x5b9af) [0x7f49462779af]
/usr/lib/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f4946267657]
/usr/lib/libpython2.7.so.1.0(+0xa8a6b) [0x7f49462c4a6b]
/usr/lib/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f4946267657]
/usr/lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x5b) [0x7f4946302c3b]
uwsgi(python_call+0x29) [0x55bb040fbd69]
uwsgi(uwsgi_request_wsgi+0x119) [0x55bb040fe2f9]
uwsgi(wsgi_req_recv+0xbe) [0x55bb0408bf9e]
uwsgi(simple_loop_run+0xd6) [0x55bb040dcdf6]
uwsgi(uwsgi_ignition+0x1d4) [0x55bb040e1fe4]
uwsgi(uwsgi_worker_run+0x2a5) [0x55bb040e6e15]
uwsgi(uwsgi_run+0x437) [0x55bb040e73b7]
uwsgi(+0x3c3e1) [0x55bb0408b3e1]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f4945c60610]
uwsgi(_start+0x29) [0x55bb0408b419]
*** end of backtrace ***
```

Thanks

**Comment by xrmx** [comment]
@dakra thanks for checking. Updated the title
