### ISSUE TITLE
If postfork fails, kill the application?

### ISSUE THREAD

**Issue by asottile** [unbit/uwsgi#1059]
I have an application which needs an expensive thing that can fail.  I'd like to move the initialization of this object from first-request-time to application-startup-time.

I cannot set it up during prefork because the objects that get initialized are not forksafe for whatever reason.
I instead opt to set it up during postfork.

The operation _can_ fail (another motivation to move it to application-startup-time is it can fail sometimes and we don't want to impact end users in this case).

From what I've seen, even if the postfork hook fails the application will continue to run (in this broken state).

Not entirely sure it's relevant but the version of uwsgi I am using is 2.0.8

Here's a log of the startup:

```
$ bin/start-dev
*** Starting uWSGI 2.0.8 (64bit) on [Sat Oct  3 14:08:24 2015] ***
compiled with version: 4.4.3 on 04 November 2014 14:36:13
os: Linux-3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015
nodename: dev25-devc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 24
current working directory: ...
writing pidfile to run/uwsgi.pid
detected binary path: .../virtualenv_run/bin/uwsgi
chdir() to ...
your memory page size is 4096 bytes
detected max file descriptor number: 10240
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "healthcheck" initialized: 2MB (key: 2136 bytes, keys: 68352 bytes, data: 2097152 bytes, bitmap: 0 bytes) preallocated ***
uWSGI http bound on :9003 fd 7
uwsgi socket 0 bound to TCP address 127.0.0.1:60790 (port auto-assigned) fd 6
Python version: 2.7.6 (python2.7_2.7.6-2+lucid1:0e6ac340ab29+, Jul 27 2015, 20:38:09)  [GCC 4.4.3]
Set PythonHome to .../virtualenv_run
Python main interpreter initialized at 0xf049f0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 402621 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
[uwsgi-signal] signum 42 registered (wid: 0 modifier1: 0 target: mule1)
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xf049f0 pid: 1244080 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1244080)
spawned uWSGI worker 1 (pid: 1244140, cores: 1)
spawned uWSGI worker 2 (pid: 1244141, cores: 1)
cache sweeper thread enabled
*** Stats server enabled on :9004 fd: 29 ***
spawned uWSGI mule 1 (pid: 1244143)
spawned uWSGI mule 2 (pid: 1244144)
spawned uWSGI http 1 (pid: 1244145)
Traceback (most recent call last):
  File ".../virtualenv_run/lib/python2.7/site-packages/uwsgidecorators.py", line 68, in postfork_chain_hook
    f()
  File ".../virtualenv_run/lib/python2.7/site-packages/uwsgidecorators.py", line 87, in __call__
    return self.f()
  File "www_pages.wsgi", line 24, in postfork
    perform_postfork_warmup()
  File "./www_pages/webapp.py", line 125, in perform_postfork_warmup
    assert False
AssertionError
Traceback (most recent call last):
  File ".../virtualenv_run/lib/python2.7/site-packages/uwsgidecorators.py", line 68, in postfork_chain_hook
    f()
  File ".../virtualenv_run/lib/python2.7/site-packages/uwsgidecorators.py", line 87, in __call__
    return self.f()
  File "www_pages.wsgi", line 24, in postfork
    perform_postfork_warmup()
  File "./www_pages/webapp.py", line 125, in perform_postfork_warmup
    assert False
AssertionError
Python auto-reloader enabled
Traceback (most recent call last):
  File ".../virtualenv_run/lib/python2.7/site-packages/uwsgidecorators.py", line 68, in postfork_chain_hook
    f()
  File ".../virtualenv_run/lib/python2.7/site-packages/uwsgidecorators.py", line 87, in __call__
    return self.f()
  File "www_pages.wsgi", line 24, in postfork
    perform_postfork_warmup()
  File ".../virtualenv_run/lib/python2.7/site-packages/yelp_lib/decorators.py", line 192, in __call__
    value = self.func(*args, **kwargs)
  File "./www_pages/webapp.py", line 125, in perform_postfork_warmup
    assert False
AssertionError
Traceback (most recent call last):
  File ".../virtualenv_run/lib/python2.7/site-packages/uwsgidecorators.py", line 68, in postfork_chain_hook
    f()
  File ".../virtualenv_run/lib/python2.7/site-packages/uwsgidecorators.py", line 87, in __call__
    return self.f()
  File "www_pages.wsgi", line 24, in postfork
    perform_postfork_warmup()
  File ".../virtualenv_run/lib/python2.7/site-packages/yelp_lib/decorators.py", line 192, in __call__
    value = self.func(*args, **kwargs)
  File "./www_pages/webapp.py", line 125, in perform_postfork_warmup
    assert False
AssertionError
...
# I can continue to hit pages and serve requests, despite the postfork functions failing
```

**Comment by xrmx** [comment]
Does calling uwsgi.stop() work for you?

**Comment by asottile** [comment]
A decorator around my postfork that looks like this:

```python
def kill_uwsgi_on_failure(func):
    @functools.wraps(func)
    def inner():
        try:
            return func()
        except Exception:
            # TODO: log
            import uwsgi
            uwsgi.stop()
    return inner
```

Does not kill uwsgi, but instead leaves it in a weird unusable state where making a request causes the app to block indefinitely.

Output that looks like this:

```
bin/start-dev
*** Starting uWSGI 2.0.8 (64bit) on [Sun Oct  4 20:28:15 2015] ***
compiled with version: 4.4.3 on 04 November 2014 14:36:13
os: Linux-3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015
nodename: dev25-devc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 24
current working directory: ...
writing pidfile to run/uwsgi.pid
detected binary path: .../virtualenv_run/bin/uwsgi
chdir() to ...
your memory page size is 4096 bytes
detected max file descriptor number: 10240
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "healthcheck" initialized: 2MB (key: 2136 bytes, keys: 68352 bytes, data: 2097152 bytes, bitmap: 0 bytes) preallocated ***
uWSGI http bound on :9003 fd 7
uwsgi socket 0 bound to TCP address 127.0.0.1:55095 (port auto-assigned) fd 6
Python version: 2.7.6 (python2.7_2.7.6-2+lucid1:0e6ac340ab29+, Jul 27 2015, 20:38:09)  [GCC 4.4.3]
Set PythonHome to .../virtualenv_run
Python main interpreter initialized at 0x19919f0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 402621 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
[uwsgi-signal] signum 42 registered (wid: 0 modifier1: 0 target: mule1)
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x19919f0 pid: 555513 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 555513)
spawned uWSGI worker 1 (pid: 555573, cores: 1)
spawned uWSGI worker 2 (pid: 555574, cores: 1)
cache sweeper thread enabled
*** Stats server enabled on :9004 fd: 29 ***
spawned uWSGI mule 1 (pid: 555576)
spawned uWSGI mule 2 (pid: 555577)
spawned uWSGI http 1 (pid: 555578)
gateway "uWSGI http 1" has been buried (pid: 555578)
...brutally killing workers...
mule 1 (pid: 555576) annihilated
mule 2 (pid: 555577) annihilated
Python auto-reloader enabled
# I then sent a request, and received no output
```

**Comment by xrmx** [comment]
@sottile thanks for giving it a try

**Comment by marc1n** [comment]
Any ideas on this topic? I have the same scenario problem.

**Comment by unbit** [comment]
@marc1n try sending SIGINT (with os.signal()) to uwsgi.master_pid() pid

**Comment by marc1n** [comment]
Thanks!
os.kill(uwsgi.masterpid(), signal.SIGINT) works.
But I see that I must use signal.SIGKILL if I have running threads in workers.
