### ISSUE TITLE
Python3.5 with uwsgi 

### ISSUE THREAD

**Issue by lud4ik** [unbit/uwsgi#1257]
```
[uwsgi-server]
recipe = buildout.recipe.uwsgi
version = 2.0.12
plugins = python3
output-format=ini
pythonpath-eggs-directory=/usr/share/XXX/eggs
config-uid=www-data
config-gid=www-data
config-chmod-socket=664
config-socket=/tmp/XXX-uwsgi.sock
config-master=true
config-processes=16
config-limit-post=10485760
config-buffer-size=32768
eggs =
   ${openssl:eggs}
   ${dependencies:eggs}
```
Trace
```
Python version: 3.5.0 (default, May 12 2016, 13:35:45)  [GCC 4.7.2]
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.5/site.py", line 580, in <module>
    main()
  File "/usr/lib/python3.5/site.py", line 566, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.5/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.5/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.5/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.5/sysconfig.py", line 595, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.5/sysconfig.py", line 538, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.5/sysconfig.py", line 410, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python3.5/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_m import *
ImportError: No module named '_sysconfigdata_m'
```

**Comment by xrmx** [comment]
How are you calling uwsgi?

**Comment by lud4ik** [comment]
```
/usr/share/XXX/bin/uwsgi --ini /usr/share/XXX/parts/uwsgi-server/uwsgi.ini -w app:run_app
```
If I use python3.5 do I have to bootstrap plugins spefically.
Can you just help please, what steps do I have to do to start uwsgi with python3?

**Comment by lud4ik** [comment]
It fixed by
```
sudo ln -s /usr/lib/python3.5/plat-*/_sysconfigdata_nd.py /usr/lib/python3.5/
```
It's system problem, not uwsgi
