### ISSUE TITLE
asyncio documentation needs update

### ISSUE THREAD

**Issue by radzhome** [unbit/uwsgi#1353]
http://uwsgi-docs.readthedocs.io/en/latest/asyncio.html

The last example uses aiohttp, `ClientResponse.read_and_close()` has been dropped.

`body = yield from response.read_and_close()`

Getting the following error:
```
future: <Task finished coro=<sleeping() done, defined at app.py:40> exception=AttributeError("'ClientResponse' object has no attribute 'read_and_close'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "app.py", line 44, in sleeping
    body = yield from response.read_and_close()
AttributeError: 'ClientResponse' object has no attribute 'read_and_close'
```

http://aiohttp.readthedocs.io/en/stable/changes.html

**Comment by xrmx** [comment]
@radzhome PR on https://github.com/unbit/uwsgi-docs much appreciated.
