### ISSUE TITLE
Don't log timestamp when logging to the systemd journal

### ISSUE THREAD

**Issue by gdamjan** [unbit/uwsgi#1379]
running uwsgi with `--logger systemd` still prints an uwsgi timestamp in the logs. for ex:
```
Oct 11 14:11:54 archless tcloud[23641]: [pid: 23656|app: -1|req: -1/59] 127.0.0.1 () {46 vars in 1077 bytes} [Tue Oct 11 14:11:54 2016] GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json => generated 74 bytes in 272 msecs (HTTP/2.0 200) 7 headers in 440 bytes (0 switches on core 0)
```
the timestamp is redundant since journald already stores timestamp in the journal.

Now, I now I can setup logformat, but it would be better if this is automatic. A wider problem is that a logger plugin only gets the full message and not a structure that it can format by itself.
Another problem is that the default log format is not documented.

**Comment by trentbuck** [comment]
FWIW here's the difference I see in uwsgi 2.0.19.1-debian, i.e. still not fixed.

Also I think the `CODE_*` fields should be the function that generated the log event, not the function that forward it to journald! 

```
diff --git 1/before.txt 2/after.txt
index 88a7cf0..754712f 100644
--- 1/before.txt
+++ 2/after.txt
@@ -1,22 +1,24 @@
-Fri 2023-02-10 17:08:08.912576 AEDT [s=88270e4c0aab451296b3c715e4d504a2;i=ffc860;b=f49822df610c44659a798bd44d7eef04;m=11d6ec2ce9e;t=5f452524e4ec0;x=5bc8c4e804893ca2]
+Mon 2023-02-13 14:50:05.948200 AEDT [s=88270e4c0aab451296b3c715e4d504a2;i=10026fb;b=f49822df610c44659a798bd44d7eef04;m=157da94ed31;t=5f48cbe206d52;x=2101ea19bf24c837]
+    CODE_FILE=plugins/systemd_logger/systemd_logger.c
+    CODE_FUNC=uwsgi_systemd_logger
+    CODE_LINE=13
-    MESSAGE=Fri Feb 10 17:08:08 2023 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /static/klaus.css (ip 10.194.71.2) !!!
+    MESSAGE=Mon Feb 13 14:50:05 2023 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /static/favicon.png (ip 10.194.71.2) !!!
     PRIORITY=6
-    SYSLOG_FACILITY=3
     SYSLOG_IDENTIFIER=uwsgi
     _BOOT_ID=f49822df610c44659a798bd44d7eef04
     _CAP_EFFECTIVE=0
-    _CMDLINE=uwsgi --master --processes=1 --plugin=0:python3 --module=klaus.contrib.wsgi_autoreload --disable-logging
+    _CMDLINE=uwsgi --master --processes=1 --plugin=0:python3 --module=klaus.contrib.wsgi_autoreload --disable-logging --plugin=1:systemd_logger --logger=systemd
     _COMM=uwsgi
     _EXE=/usr/bin/uwsgi-core
     _GID=65309
     _HOSTNAME=heavy
     _MACHINE_ID=b37f3232a0394a39bef0c398a4a58cdb
-    _PID=467976
+    _PID=774075
     _SELINUX_CONTEXT=unconfined
-    _STREAM_ID=226c27fedd1f4d0c90b9e948dae4e2bb
+    _SOURCE_REALTIME_TIMESTAMP=1676260205948200
     _SYSTEMD_CGROUP=/system.slice/klaus.service
-    _SYSTEMD_INVOCATION_ID=245ff57f4aab42f6a11ad829d4a57877
+    _SYSTEMD_INVOCATION_ID=20caf33d47914810b841bbcd34413f69
     _SYSTEMD_SLICE=system.slice
     _SYSTEMD_UNIT=klaus.service
-    _TRANSPORT=stdout
+    _TRANSPORT=journal
     _UID=65309
```

**Comment by trentbuck** [comment]
PS: looking at the actual code, I think it's sending one journal event for every line of text.

https://github.com/unbit/uwsgi/blame/master/plugins/systemd_logger/systemd_logger.c#L7-L12

I think that's a mistake -- a journal event can (and often is) multi-line.  For example, here's one:

```
Jan 17 14:06:25 heavy monit[4471]: 'REDACTED-ssh-check_ntp_peer' status failed (1) -- Traceback (most recent call last):
                                     File "/etc/scripts/nagios-remote.py", line 80, in <module>
                                       config.read_string(
                                     File "/usr/lib/python3.9/configparser.py", line 723, in read_string
                                       self.read_file(sfile, source)
                                     File "/usr/lib/python3.9/configparser.py", line 718, in read_file
                                       self._read(f, source)
                                     File "/usr/lib/python3.9/configparser.py", line 1093, in _read
                                       raise DuplicateOptionError(sectname, optname,
                                   configparser.DuplicateOptionError: While reading from '/etc/nagios/nrpe_local.cfg' [line 23]: option 'command[check_study]' in section 'local' already exists
```

I think it is extremely useful to keep all the lines of a backtrace together in a single event!

**Comment by trentbuck** [comment]
OK, I dug through the source code a bit more.
To fix the immediate issue, you just need `--log-date=` i.e. setting it to the empty string.

Here's the control flow I traced:

- https://github.com/unbit/uwsgi/blob/ffced3256e6de7e841e4ca038620437f3c8042c0/core/uwsgi.c#L1215
- https://github.com/unbit/uwsgi/blob/d58a832c81c2c96ae0f6e72614e1cc47f4b5d332/core/logging.c#L77
- https://github.com/unbit/uwsgi/blob/d58a832c81c2c96ae0f6e72614e1cc47f4b5d332/core/logging.c#L88-L94
- https://github.com/unbit/uwsgi/blob/ffced3256e6de7e841e4ca038620437f3c8042c0/core/uwsgi.c#L4689-L4697

Here's the exact command I tested:

```
ExecStart=uwsgi --master --processes=1 --plugin=0:python3 --module=klaus.contrib.wsgi_autoreload --disable-logging --plugin=1:systemd_logger --logger=systemd --log-date=
```

Here's the output I get now:

```
Feb 13 16:40:00 heavy uwsgi[845657]:  - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /favicon.ico (ip 10.194.71.2) !!!
Feb 13 16:40:00 heavy uwsgi[845657]:  - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /favicon.ico (10.194.71.2)
Feb 13 16:40:00 heavy uwsgi[845657]: OSError: write error
Feb 13 16:40:00 heavy uwsgi[845657]:  - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /favicon.ico/ (ip 10.194.71.2) !!!
Feb 13 16:40:00 heavy uwsgi[845657]:  - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /favicon.ico/ (10.194.71.2)
Feb 13 16:40:00 heavy uwsgi[845657]: OSError: write error
```

**Comment by gdamjan** [comment]
I ended up setting
```
logformat = %(addr) (%(user)) (%(proto) %(status)) %(method) %(uri) => generated %(rsize) bytes in %(msecs) msecs %(headers) headers in %(hsize) bytes {%(vars) vars in %(pktsize) bytes} (%(switches) switches on core %(core))
```
