### ISSUE TITLE
"ValueError: filedescriptor out of range in select()" appear when open a lot of long connection

### ISSUE THREAD

**Issue by JianMingZhuo** [unbit/uwsgi#1475]
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/engineio/async_gevent_uwsgi.py", line 52, in select_greenlet_runner
    select([fd], [], [])[0]
  File "/usr/local/lib/python2.7/dist-packages/gevent/select.py", line 141, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
ValueError: filedescriptor out of range in select()
Mon Feb 27 17:07:49 2017 <Greenlet at 0x7faeadac3e10: select_greenlet_runner(5228, <gevent.event.Event object at 0x7faeada83d50>)> failed with ValueError
```

I get this exception when my uwsgi get about 10,000 long connection.

I start uwsgi like this 
```
uwsgi --http :5000 --gevent 65536  -p 4 --http-websockets --master --wsgi-file test.py --callable app --listen 10240 --socket-timeout 3600 --harakiri 3600 --http-timeout 3600 --http-stats-server 127.0.0.1:8888 --disable-logging
```

**Comment by unbit** [comment]
Have you raised the maximum number of file descriptors in your system ?

**Comment by JianMingZhuo** [comment]
Yes, I changed maximum number of file descriptors to 65536.

My system is Ubuntu 16 on VMware.

Here is my `/etc/security/limits.conf`

```
*                soft    nofile          65536
*                hard    nofile          65536
www-data         soft    nofile          65536
www-data         hard    nofile          65536
root             soft    nofile          65536
root             hard    nofile          65536
```

I can see `65536` after input `ulimit -n`

**Comment by unbit** [comment]
This enforces only shell sessions. You should use the --max-fd option of uWSGI and tune the /proc file

**Comment by JianMingZhuo** [comment]
Is seem the number of fd has been 65535.

I used root for test.
```
root@ubuntu:/home/jeff/Documents/test# uwsgi --http :5000 --gevent 65536  -p 4 --http-websockets --master --wsgi-file test.py --callable app --listen 10240 --socket-timeout 3600 --harakiri 3600 --http-timeout 3600 --http-stats-server 127.0.0.1:8888 --disable-logging
*** Starting uWSGI 2.0.14 (64bit) on [Mon Feb 27 17:34:59 2017] ***
compiled with version: 5.4.0 20160609 on 23 February 2017 10:06:45
os: Linux-4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/jeff/Documents/test
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 23648
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 65536
- async cores set to 65536 - fd table size: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:35636 (port auto-assigned) fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x2027350
python threads support enabled
your server socket listen backlog is limited to 10240 connections
your mercy for graceful operations on workers is 60 seconds
mapped 3376727040 bytes (3297585 KB) for 262144 cores
*** Operational MODE: preforking+async ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2027350 pid: 3149 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3149)
spawned uWSGI worker 1 (pid: 3152, cores: 65536)
spawned uWSGI worker 2 (pid: 3153, cores: 65536)
spawned uWSGI worker 3 (pid: 3154, cores: 65536)
spawned uWSGI worker 4 (pid: 3155, cores: 65536)
spawned uWSGI http 1 (pid: 3156)
*** http stats server enabled on 127.0.0.1:8888 fd: 7 ***
*** running gevent loop engine [addr:0x493860] ***
```

```
root@ubuntu:/proc/3152# cat limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             23648                23648                processes 
Max open files            65536                65536                files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       23648                23648                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us  
```

**Comment by JianMingZhuo** [comment]
I use flask + flask-SocketIO + gevent + uwsgi as the server. It seems gevent used `select()`，and `select()` limit 1024 fd.  
So the only way for me is  add more processes?

**Comment by unbit** [comment]
can't you force the use of epoll() ?

**Comment by JianMingZhuo** [comment]
Thanks!!!!!! 
I found than flask-SocketIO base on the python-engineio, and python-engineio use ```select()```
