### ISSUE TITLE
Updating uWSGI fails with IOError: [Errno 26] Text file busy: '/usr/local/bin/uwsgi'

### ISSUE THREAD

**Issue by tobiasdam** [unbit/uwsgi#1531]
Updating an old version of uwsgi (`1.9.2`) to version `2.0.15` via `pip 9.0.1` fails to replace `/usr/local/bin/uwsgi`:
```python
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 26] Text file busy: '/usr/local/bin/uwsgi'
```
The issue might be caused by not unlinking the file beforehand.

However, I am not entirely sure if this is an issue of the uwsgi setup, because the update procedure works fine using `pip 1.5.6` from the `python-pip` Raspbian Jessie repository.

This behaviour results in pip thinking it updated uwsgi properly, the next time I try to install the new uwsgi version and in the uwsgi executable not being updated.

**Comment by xrmx** [comment]
Is this a *very* old distro?

**Comment by tobiasdam** [comment]
I used the current Raspbian Jessie image, so it's Debian 8

**Comment by tobiasdam** [comment]
I forgot to mention that this only happens, if uwsgi is running while updating via pip

**Comment by blairg23** [comment]
I had this problem when I had uWSGI installed via `apt` and then tried to do a `pip install uwsgi --upgrade --ignore-installed`. I fixed by removing the `--ignore-installed` bit and rerunning.
