### ISSUE TITLE
signal handler fails with gevent + python3.5

### ISSUE THREAD

**Issue by almaslov** [unbit/uwsgi#1574]
Hello!
I've got an issue after switching python from 3.4 to 3.5. When using with gevent plugin, uwsgi fails to terminate with SIGINT or SIGTERM signal, so the only solution is SIGKILL.

It can be reproduced on 2.0.15 base build:

`# ./uwsgi --gevent 10 -s :80 --die-on-term
*** Starting uWSGI 2.0.15 (64bit) on [Thu Jul  6 19:20:13 2017] ***
compiled with version: 5.3.1 20160406 (Red Hat 5.3.1-6) on 06 July 2017 18:28:59
os: Linux-4.9.27-moby #1 SMP Thu May 11 04:01:18 UTC 2017
nodename: 75eee412b3cd
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /uwsgi
detected binary path: /uwsgi/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
- async cores set to 10 - fd table size: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :80 fd 3
Python version: 3.5.1 (default, Oct 22 2016, 08:10:47)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
Python main interpreter initialized at 0x170a670
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 165504 bytes (161 KB) for 10 cores
*** Operational MODE: async ***
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 22062, cores: 10)
*** running gevent loop engine [addr:0x48fb10] ***

^CBrutally killing worker 1 (pid: 22062)...
Thu Jul  6 19:20:17 2017 - stopping gevent signals watchers for worker 1 (pid: 22062)...
Thu Jul  6 19:20:17 2017 - stopping gevent sockets watchers for worker 1 (pid: 22062)...
Thu Jul  6 19:20:17 2017 - main gevent watchers stopped for worker 1 (pid: 22062)...
SystemError: null argument to internal routine

During handling of the above exception, another exception occurred:

SystemError: <built-in method stop of gevent.libev.corecext.io object at 0x7f0b7b9035f8> returned a result with an error set

During handling of the above exception, another exception occurred:

SystemError: PyEval_EvalFrameEx returned a result with an error set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages/gevent/hub.py", line 279, in handle
    self.handler(*self.args, **self.kwargs)
SystemError: <built-in function uwsgi_gevent_unix_signal_int_handler> returned a result with an error set
Thu Jul  6 19:20:17 2017
SystemError: null argument to internal routine

During handling of the above exception, another exception occurred:

SystemError: <built-in method stop of gevent.libev.corecext.io object at 0x7f0b7b9035f8> returned a result with an error set

During handling of the above exception, another exception occurred:

SystemError: PyEval_EvalFrameEx returned a result with an error set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages/gevent/greenlet.py", line 496, in join
    result = self.parent.switch()
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
SystemError: <built-in function uwsgi_gevent_unix_signal_int_handler> returned a result with an error set
`

**Comment by almaslov** [comment]
I found out that this bug is not actually related to python version. It is caused by calling PyObject_CallMethod with null pointer as object.
https://github.com/unbit/uwsgi/pull/1586 will fix it.
