### ISSUE TITLE
uwsgi.websocket_send fails on messages >200-255kb

### ISSUE THREAD

**Issue by kylemacfarlane** [unbit/uwsgi#1602]
Using uWSGI 2.0.15.

My WSGI script is a copy of: https://github.com/unbit/uwsgi/blob/2.0.15/tests/websockets_chat_async.py

I run it with:

```
uwsgi --socket /sockets/dev.websocket.sock --wsgi-file bin/websocket.wsgi --master --single-interpreter --chmod-socket=777 --async 10 --ugreen
```

When I try to send messages >200-255kb I get the following error:

```
uwsgi_response_write_body_do() TIMEOUT !!!
Traceback (most recent call last):
  File "/vagrant/src/app/wsgi_websocket.py", line 88, in application
    _handle_output(msg)
  File "/vagrant/src/app/wsgi_websocket.py", line 45, in _handle_output
    uwsgi.websocket_send(json.dumps(msg, separators=(',', ':')))
OSError: unable to send websocket message
```

1) This "timeout" happens immediately - not after 60s and is not affected by `uwsgi_read_timeout `.

2) The max size that can be sent varies each time uWSGI is started but it always seems to be between 200-255kb.

3) I've tried increasing options like `ugreen-stacksize` and `websockets-max-size` but they have no affect.

**Comment by kylemacfarlane** [comment]
This issue doesn't seem to exist if uwsgi is accessed directly by running with `--http`. This means it must be an nginx setting but I can't figure out what it could be. Adjusting `uwsgi_buffers` or even completely turning off `uwsgi_buffering` don't help.

**Comment by funkybob** [comment]
Does it make any difference if you enable post-buffering ?

**Comment by kylemacfarlane** [comment]
Websockets won't even connect when I use `--post-buffering`.

**Comment by lucasdavid** [comment]
Did you manage to fix this? I'm also having this issue.

**Comment by kylemacfarlane** [comment]
@lucasdavid I never managed to completely fix it but for me it's pretty rare in production. I think it's something related to #1716 combined with some nginx setting.

**Comment by funkybob** [comment]
Does it still happen in 2.0.16?

**Comment by kylemacfarlane** [comment]
@funkybob I haven't tested 2.0.16 but it was still happening in master from mid-January.

I did find that switching from ugreen to gevent reduced the errors but didn't completely fix it like I claimed in #1716.
