### ISSUE TITLE
!restart causes bot to crash?

### ISSUE THREAD

**Issue by Ryutsuke** [unbit/uwsgi#1698]
Hello I've followed the setup instructions step by step everything seems to work bot plays music just fine in my discord. 

This is the error I get I have no idea what this means.    :(

Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.5/site.py", line 580, in <module>
    main()
  File "/usr/lib/python3.5/site.py", line 566, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.5/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.5/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.5/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.5/sysconfig.py", line 595, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.5/sysconfig.py", line 538, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.5/sysconfig.py", line 410, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python3.5/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_m import *
ImportError: No module named '_sysconfigdata_m'

**Comment by xrmx** [comment]
Looks like a dup of https://github.com/unbit/uwsgi/issues/1257 . What system is this?

**Comment by Ryutsuke** [comment]
The suggested fix in #1257 Did not work for me still get that error when I try to restart the bot.

**Comment by Ryutsuke** [comment]
Does anyone have an answer to this? I've ran the MusicBot on my Windows 10 computer and it runs just run the !restart command works perfectly bot leaves and reconnects. When running on my RaspberryPi it shows this message and crashes.

Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.5/site.py", line 563, in <module>
    main()
  File "/usr/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.5/sysconfig.py", line 595, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.5/sysconfig.py", line 538, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.5/sysconfig.py", line 410, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python3.5/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_m import *
ImportError: No module named '_sysconfigdata_m'
pi@raspberrypi:~/MusicBot $

**Comment by Ryutsuke** [comment]
SOLVED!!! So it turns out even with a fresh install of raspbian and install everything in the MusicBot guide if your python --version shows 2.7.3 like mine you need to purge it so it will default to 3.5.3. that got rid of the trace error for me.
