### ISSUE TITLE
Asyncio with processes > 1 causes epoll fd issue

### ISSUE THREAD

**Issue by shanecarey17** [unbit/uwsgi#1713]
When running with the following configuration

```
[uwsgi]
 http = :5000
 stats = :5001
 stats-http = true
 asyncio = 100
 master = true
 greenlet = true
 http-websockets = true
 processes = 2
```

One of the worker processes continually attempts to register the socket fd and dies repeatedly

```
[uWSGI] getting INI configuration from config.ini
*** Starting uWSGI 2.0.15 (64bit) on [Tue Jan  9 21:59:47 2018] ***
compiled with version: 5.3.0 on 22 December 2017 17:47:28
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: 87d4844a6d59
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /fills
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
- async cores set to 100 - fd table size: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :5000 fd 4
**uwsgi socket 0 bound to TCP address 127.0.0.1:43323 (port auto-assigned) fd 3**
Python version: 3.5.4 (default, Aug  9 2017, 21:04:42)  [GCC 5.3.0]
Python main interpreter initialized at 0x7fa0b6941960
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 3278592 bytes (3201 KB) for 200 cores
*** Operational MODE: preforking+async ***
[2018-01-09 21:59:47,572] {base_connection.py:212} INFO - Connecting to 10.9.62.115:5672
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7fa0b6941960 pid: 7 (default app)
enabled greenlet engine
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7)
spawned uWSGI worker 1 (pid: 18, cores: 100)
spawned uWSGI worker 2 (pid: 19, cores: 100)
*** Stats server enabled on :5001 fd: 20 ***
spawned uWSGI http 1 (pid: 20)
*** running asyncio loop engine [addr:0x7fa0b629b8b0] ***
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 264, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.5/selectors.py", line 191, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '3 is not registered'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 337, in add_reader
    return self._add_reader(fd, callback, *args)
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 267, in _add_reader
    (handle, None))
  File "/usr/local/lib/python3.5/selectors.py", line 412, in register
    self._epoll.register(key.fd, epoll_events)
FileExistsError: [Errno 17] File exists
DAMN ! worker 1 (pid: 18) died :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 21)
*** running asyncio loop engine [addr:0x7fa0b629b8b0] ***
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 264, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.5/selectors.py", line 191, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '3 is not registered'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 337, in add_reader
    return self._add_reader(fd, callback, *args)
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 267, in _add_reader
    (handle, None))
  File "/usr/local/lib/python3.5/selectors.py", line 412, in register
    self._epoll.register(key.fd, epoll_events)
FileExistsError: [Errno 17] File exists
```

I am not entirely sure what the socket referred to in this line is
```
uwsgi socket 0 bound to TCP address 127.0.0.1:43323 (port auto-assigned) fd 3
```

but it is being passed to each worker to be registered in the asyncio event loop, which causes this issue at this line in python's select module https://github.com/python/cpython/blob/3.5/Modules/selectmodule.c#L1414

**Comment by funkybob** [comment]
Does it still behave the same if you add `lazy-apps = true` to your INI file?
