### ISSUE TITLE
Error on uwsgi worker spawn

### ISSUE THREAD

**Issue by wsYdd** [unbit/uwsgi#1721]
I use nginx + uwsgi +django，I find the same [problem](http://lists.unbit.it/pipermail/uwsgi/2017-June/008728.html)，why?

`Traceback (most recent call last):
  File "/home/admin/anaconda2/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    signals.request_started.send(sender=self.__class__, environ=environ)
 File "/home/admin/anaconda2/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/admin/anaconda2/lib/python2.7/site-packages/django/db/__init__.py", line 61, in close_old_connections
    conn.close_if_unusable_or_obsolete()
  File "/home/admin/anaconda2/lib/python2.7/site-packages/django/db/backends/base/base.py", line 504, in close_if_unusable_or_obsolete
    self.close()
  File "/home/admin/anaconda2/lib/python2.7/site-packages/django/db/backends/base/base.py", line 272, in close
    self._close()
  File "/home/admin/anaconda2/lib/python2.7/site-packages/django/db/backends/base/base.py", line 221, in _close
    return self.connection.close()
  File "/home/admin/anaconda2/lib/python2.7/site-packages/pymysql/connections.py", line 734, in close
    sock.close()
AttributeError: 'NoneType' object has no attribute 'close'`

**Comment by xrmx** [comment]
Maybe you are doing silly in your application? Better ask on a django related forum.
