### ISSUE TITLE
Python3 module should convert env vars

### ISSUE THREAD

**Issue by jpic** [unbit/uwsgi#1897]
Is there any way to make uwsgi not to printout a traceback for every single env var on python 3 ? example :

```                      
    *** Operational MODE: preforking ***
    b'DB_ENGINE' b'django.db.backends.postgresql'
    Traceback (most recent call last):
      File "/usr/lib/python3.6/os.py", line 674, in __setitem__
        key = self.encodekey(key)
      File "/usr/lib/python3.6/os.py", line 745, in encode
        raise TypeError("str expected, not %s" % type(value).__name__)
    TypeError: str expected, not bytes
    b'PYTHONIOENCODING' b'UTF-8'
    Traceback (most recent call last):
      File "/usr/lib/python3.6/os.py", line 674, in __setitem__
        key = self.encodekey(key)
      File "/usr/lib/python3.6/os.py", line 745, in encode
        raise TypeError("str expected, not %s" % type(value).__name__)
    TypeError: str expected, not bytes
    ...
```

Note that you see my print statement of key and value before each traceback, that was inserted above     key = self.encodekey(key).

This happens for each --env argument when the python3 module is used.

**Comment by jpic** [comment]
Dupe of  #1143
