### ISSUE TITLE
PHP plugin compiled with GCC 8.2.0 segfaults with PHP >= 7.1

### ISSUE THREAD

**Issue by cjmayo** [unbit/uwsgi#1960]
Create info.php:
```
<?php phpinfo() ?>
```

Serve with:
```
uwsgi --http-socket :3031 --http-socket-modifier1 14 --plugin php71 --php-app info.php
```
Browse http://localhost:3031/:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff19e2fd1 in memcpy (__len=1040, __src=0x7ffff22af5e0 <global_orig_handlers>, 
    __dest=<optimized out>) at /usr/include/bits/string_fortified.h:34
34	  return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
(gdb) bt
#0  0x00007ffff19e2fd1 in memcpy (__len=1040, __src=0x7ffff22af5e0 <global_orig_handlers>, 
    __dest=<optimized out>) at /usr/include/bits/string_fortified.h:34
#1  zend_signal_activate ()
    at /var/tmp/portage/dev-lang/php-7.1.26/work/sapis-build/embed/Zend/zend_signal.c:325
#2  0x00007ffff193ebc5 in php_request_startup ()
    at /var/tmp/portage/dev-lang/php-7.1.26/work/sapis-build/embed/main/main.c:1664
#3  0x00007ffff22b7577 in uwsgi_php_request (wsgi_req=<optimized out>) at plugins/php/php_plugin.c:1069
#4  0x000055555558201b in wsgi_req_recv (queue=queue@entry=5, wsgi_req=wsgi_req@entry=0x7ffff7fc6078)
    at core/utils.c:1432
#5  0x00005555555cf4d4 in simple_loop_run (arg1=0x0) at core/loop.c:146
#6  0x00005555555cf2a0 in simple_loop () at core/loop.c:62
#7  0x00005555555d4011 in uwsgi_ignition () at core/uwsgi.c:3613
#8  0x00005555555d7920 in uwsgi_worker_run () at core/uwsgi.c:3541
#9  0x00005555555d7eb1 in uwsgi_run () at core/uwsgi.c:3451
#10 0x000055555558160e in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>)
    at core/uwsgi.c:2045
```

PHP 7.2 also fails.
This is with uWSGI 2.0.17.1, also with uwsgi-2.0 branch at 83a5e82a8f77ef3ea7d6c79613af8516cebccd00 plus 7e96e3616e08cd5500 and versions of the emperor and mule patches in #1856 (compiles OK with -Werror).

PHP 7.0 works.

PHP 7.2 plus uWSGI 2.0.17.1 compiled with GCC 7.3.0 works.

This is on Gentoo Linux.

**Comment by xrmx** [comment]
Could you please test uwsgi-2.0 with GCC 7.3.0? If it fails then please bisect something in between 2.0.17.1 and that. If it works then there's most probably something wrong in #1856

**Comment by cjmayo** [comment]
uwsgi-2.0 with GCC 7.3.0 works.
uwsgi-2.0 with GCC 8.2.0 fails. (i.e. at 83a5e82a8f77ef3ea7d6c79613af8516cebccd00 without any additional patches from #1856)

**Comment by xrmx** [comment]
@cjmayo thanks for testing! So it looks like 7e96e3616e08cd55001525e2a097c2b0e61d9141 is the buggy one.

**Comment by xrmx** [comment]
@cjmayo could you please give it a try to https://github.com/xrmx/uwsgi/tree/fixcomp2 please? You can cherry pick the commits to uwsgi-2.0 if you prefer.

**Comment by cjmayo** [comment]
Tried uwsgi-2.0 at d1300caec5f378 with e38ff0132498313b1859dedf4ceb683112d4c0ac
fails with:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff19e2fd1 in memcpy (__len=1040, __src=0x7ffff22af5e0 <global_orig_handlers>, __dest=<optimized out>)
    at /usr/include/bits/string_fortified.h:34
34	  return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
(gdb) bt
#0  0x00007ffff19e2fd1 in memcpy (__len=1040, __src=0x7ffff22af5e0 <global_orig_handlers>, __dest=<optimized out>)
    at /usr/include/bits/string_fortified.h:34
#1  zend_signal_activate () at /var/tmp/portage/dev-lang/php-7.1.26/work/sapis-build/embed/Zend/zend_signal.c:325
#2  0x00007ffff193ebc5 in php_request_startup () at /var/tmp/portage/dev-lang/php-7.1.26/work/sapis-build/embed/main/main.c:1664
#3  0x00007ffff22b7537 in uwsgi_php_request () from /usr/lib64/uwsgi/php71_plugin.so
#4  0x000055555558200b in wsgi_req_recv ()
#5  0x00005555555cef74 in simple_loop_run ()
#6  0x00005555555ced50 in simple_loop ()
#7  0x00005555555d3a91 in uwsgi_ignition ()
#8  0x00005555555d71a0 in uwsgi_worker_run ()
#9  0x00005555555d7731 in uwsgi_run ()
#10 0x00005555555815fe in main ()
```

I tried using fixcomp2 but the uwsgi command line arguments have changed? uwsgi runs but exits immediately with `*** no app loaded. GAME OVER ***`.

**Comment by xrmx** [comment]
@cjmayo I've compiled it with make php against php 7.3.1 and it works fine for me here.

**Comment by cjmayo** [comment]
Still have the same problem with php 7.3.1. At the point of browsing valgrind outputs:

```
==23524== Invalid read of size 8
==23524==    at 0xB2054BC: memcpy (string_fortified.h:34)
==23524==    by 0xB2054BC: zend_signal_activate (zend_signal.c:323)
==23524==    by 0xB166BC9: php_request_startup (main.c:1791)
==23524==    by 0xAB60576: uwsgi_php_request (php_plugin.c:1069)
==23524==    by 0x13605A: wsgi_req_recv (utils.c:1432)
==23524==    by 0x1835E3: simple_loop_run (loop.c:146)
==23524==    by 0x1833AF: simple_loop (loop.c:62)
==23524==    by 0x188120: uwsgi_ignition (uwsgi.c:3607)
==23524==    by 0x18BA2F: uwsgi_worker_run (uwsgi.c:3535)
==23524==    by 0x18BFC0: uwsgi_run (uwsgi.c:3445)
==23524==    by 0x13564D: main (uwsgi.c:2046)
==23524==  Address 0xe8a2c58 is 8 bytes before a block of size 336 alloc'd
==23524==    at 0x4C3139B: realloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==23524==    by 0xB164918: ts_allocate_id (TSRM.c:271)
==23524==    by 0xE611592: accel_startup (ZendAccelerator.c:2758)
==23524==    by 0xB1E4E24: zend_extension_startup (zend_extensions.c:187)
==23524==    by 0xB1CBC9D: zend_llist_apply_with_del (zend_llist.c:169)
==23524==    by 0xB1E4F96: zend_startup_extensions (zend_extensions.c:208)
==23524==    by 0xB167F97: php_module_startup (main.c:2336)
==23524==    by 0xAB5EC7B: php_uwsgi_startup (php_plugin.c:625)
==23524==    by 0xAB5F9E8: uwsgi_php_init (php_plugin.c:715)
==23524==    by 0x1890BD: uwsgi_start (uwsgi.c:2859)
==23524==    by 0x18B663: uwsgi_setup (uwsgi.c:2545)
==23524==    by 0x135648: main (uwsgi.c:2045)
==23524== 
==23524== Invalid write of size 8
==23524==    at 0xB2054C8: memcpy (string_fortified.h:34)
==23524==    by 0xB2054C8: zend_signal_activate (zend_signal.c:323)
==23524==    by 0xB166BC9: php_request_startup (main.c:1791)
==23524==    by 0xAB60576: uwsgi_php_request (php_plugin.c:1069)
==23524==    by 0x13605A: wsgi_req_recv (utils.c:1432)
==23524==    by 0x1835E3: simple_loop_run (loop.c:146)
==23524==    by 0x1833AF: simple_loop (loop.c:62)
==23524==    by 0x188120: uwsgi_ignition (uwsgi.c:3607)
==23524==    by 0x18BA2F: uwsgi_worker_run (uwsgi.c:3535)
==23524==    by 0x18BFC0: uwsgi_run (uwsgi.c:3445)
==23524==    by 0x13564D: main (uwsgi.c:2046)
==23524==  Address 0x18 is not stack'd, malloc'd or (recently) free'd
==23524== 
!!! uWSGI process 23524 got Segmentation Fault !!!
*** backtrace of 23524 ***
/usr/bin/uwsgi(uwsgi_backtrace+0x2a) [0x1879ca]
/usr/bin/uwsgi(uwsgi_segfault+0x23) [0x187dc3]
/lib64/libc.so.6(+0x387f0) [0x697d7f0]
/usr/lib64/php7.3/lib64/libphp7.so(+0x4a24c8) [0xb2054c8]
/usr/lib64/php7.3/lib64/libphp7.so(php_request_startup+0x10a) [0xb166bca]
/usr/lib64/uwsgi/php73_plugin.so(uwsgi_php_request+0x957) [0xab60577]
/usr/bin/uwsgi(wsgi_req_recv+0xab) [0x13605b]
/usr/bin/uwsgi(simple_loop_run+0xc4) [0x1835e4]
/usr/bin/uwsgi(simple_loop+0x10) [0x1833b0]
/usr/bin/uwsgi(uwsgi_ignition+0x2a1) [0x188121]
/usr/bin/uwsgi(uwsgi_worker_run+0x260) [0x18ba30]
/usr/bin/uwsgi(uwsgi_run+0x461) [0x18bfc1]
/usr/bin/uwsgi(+0x2d64e) [0x13564e]
/lib64/libc.so.6(__libc_start_main+0xeb) [0x69683cb]
/usr/bin/uwsgi(_start+0x2a) [0x13567a]
*** end of backtrace ***
```

**Comment by xrmx** [comment]
@cjmayo i think you need to poke at php source code and find out what's in zend_signal.c line 323 to sort out if the issue is in something uwsgi is passing to it or just a php issue.

**Comment by DevelAngel** [comment]
I can confirm that segfault, too.

- Gentoo Linux (arm64; raspberry pi 3b)
- gcc-8.3.0 (sys-devel/gcc-8.3.0-r1)
- php-7.3.17
- uwsgi-2.0.18

Compiling php and uwsgi (same versions) with gcc-7.5.0 seem to work.
Compiling uwsgi with gcc-7.5 and php with gcc-8.3 does not work.
