### ISSUE TITLE
uwsgi(>=2.0.15) + lxml + dm.xmlsec.binding produces an error related to lxml

### ISSUE THREAD

**Issue by kalombos** [unbit/uwsgi#1998]
The requirements:
- dm.xmlsec.binding==1.3.7
- lxml==4.3.3
- uWSGI>=2.0.15

WSGI application code:

```import dm.xmlsec.binding as xmlsec
from lxml import etree
xmlsec.initialize()


def application(environ, start_response):
    start_response('200 OK', [('content-type', 'text/plain')])
    etree.parse("/home/kalombo/project/test/server_assets/xml/xml.xml")
    res = ["hello world"]
    return '\n'.join(res)
```

The command for running the application:

`uwsgi --http-socket :8000 --wsgi-file dugga/wsgi.py`

Then, go to http://localhost:8000/ and refresh the page until you get the error:

```
Traceback (most recent call last):
  File "dugga/wsgi.py", line 10, in application
    etree.parse("/home/kalombo/projects/Dugga/server_assets/xml/xml.xml")
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 651, in lxml.etree._raiseParseError
  File "/home/kalombo/projects/test/server_assets/xml/xml.xml", line 0
lxml.etree.XMLSyntaxError
```
It is an interesting thing that the bug won't be raised when the page has been opened for the first time. If i remove **xmlsec.initialize()** line all will work fine. It looks like this error is related to xmlsec but the bug is not yielded for gunicorn or 1.9.17.1-debian version of uwsgi

**Comment by xrmx** [comment]
Please state the exact uwsgi version you have tested and how you have installed it.

**Comment by kalombos** [comment]
I tested with 2.0.15-debian version it was installed as a linux package on Linux Mint 19 Tara and i also tested 2.0.18 version which was installed using pip. I forgot to mention that i have used python 2.7 version and i have not tested with python 3. i will check the bug with python 3 and tell about results
