### ISSUE TITLE
NameError: name 'execfile' is not defined when built from source

### ISSUE THREAD

**Issue by owen800q** [unbit/uwsgi#2073]
```
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

```
make

python uwsgiconfig.py --build 
using profile: buildconf/default.ini
detected include path: ['/usr/lib/gcc/x86_64-linux-gnu/7/include', '/usr/local/include', '/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed', '/usr/include/x86_64-linux-gnu', '/usr/include']
detected CPU cores: 4
configured CFLAGS: -O2 -I. -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -DUWSGI_HAS_IFADDRS -DUWSGI_ZLIB -DUWSGI_LOCK_USE_MUTEX -DUWSGI_EVENT_USE_EPOLL -DUWSGI_EVENT_TIMER_USE_TIMERFD -DUWSGI_EVENT_FILEMONITOR_USE_INOTIFY  -DUWSGI_PCRE -DUWSGI_ROUTING -DUWSGI_VERSION="\"2.0.18\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="18" -DUWSGI_VERSION_REVISION="0" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_SSL -I/usr/include/libxml2 -DUWSGI_XML -DUWSGI_XML_LIBXML2 -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);UDEP(ping);UDEP(cache);UDEP(nagios);UDEP(rrdtool);UDEP(carbon);UDEP(rpc);UDEP(corerouter);UDEP(fastrouter);UDEP(http);UDEP(ugreen);UDEP(signal);UDEP(syslog);UDEP(rsyslog);UDEP(logsocket);UDEP(router_uwsgi);UDEP(router_redirect);UDEP(router_basicauth);UDEP(zergpool);UDEP(redislog);UDEP(mongodblog);UDEP(router_rewrite);UDEP(router_http);UDEP(logfile);UDEP(router_cache);UDEP(rawrouter);UDEP(router_static);UDEP(sslrouter);UDEP(spooler);UDEP(cheaper_busyness);UDEP(symcall);UDEP(transformation_tofile);UDEP(transformation_gzip);UDEP(transformation_chunked);UDEP(transformation_offload);UDEP(router_memcached);UDEP(router_redis);UDEP(router_hash);UDEP(router_expires);UDEP(router_metrics);UDEP(transformation_template);UDEP(stats_pusher_socket);" -DUWSGI_LOAD_EMBEDDED_PLUGINS="ULEP(python);ULEP(gevent);ULEP(ping);ULEP(cache);ULEP(nagios);ULEP(rrdtool);ULEP(carbon);ULEP(rpc);ULEP(corerouter);ULEP(fastrouter);ULEP(http);ULEP(ugreen);ULEP(signal);ULEP(syslog);ULEP(rsyslog);ULEP(logsocket);ULEP(router_uwsgi);ULEP(router_redirect);ULEP(router_basicauth);ULEP(zergpool);ULEP(redislog);ULEP(mongodblog);ULEP(router_rewrite);ULEP(router_http);ULEP(logfile);ULEP(router_cache);ULEP(rawrouter);ULEP(router_static);ULEP(sslrouter);ULEP(spooler);ULEP(cheaper_busyness);ULEP(symcall);ULEP(transformation_tofile);ULEP(transformation_gzip);ULEP(transformation_chunked);ULEP(transformation_offload);ULEP(router_memcached);ULEP(router_redis);ULEP(router_hash);ULEP(router_expires);ULEP(router_metrics);ULEP(transformation_template);ULEP(stats_pusher_socket);"
*** uWSGI compiling server core ***
[thread 0][gcc -pthread] core/utils.o
[thread 1][gcc -pthread] core/protocol.o
[thread 2][gcc -pthread] core/socket.o
[thread 3][gcc -pthread] core/logging.o
[thread 1][gcc -pthread] core/master.o
[thread 2][gcc -pthread] core/master_utils.o
[thread 3][gcc -pthread] core/emperor.o
[thread 1][gcc -pthread] core/notify.o
[thread 0][gcc -pthread] core/mule.o
[thread 2][gcc -pthread] core/subscription.o
[thread 1][gcc -pthread] core/stats.o
[thread 3][gcc -pthread] core/sendfile.o
[thread 0][gcc -pthread] core/async.o
[thread 3][gcc -pthread] core/master_checks.o
[thread 1][gcc -pthread] core/fifo.o
[thread 2][gcc -pthread] core/offload.o
[thread 0][gcc -pthread] core/io.o
[thread 1][gcc -pthread] core/static.o
[thread 3][gcc -pthread] core/websockets.o
[thread 2][gcc -pthread] core/spooler.o
[thread 3][gcc -pthread] core/snmp.o
[thread 1][gcc -pthread] core/exceptions.o
[thread 2][gcc -pthread] core/config.o
[thread 0][gcc -pthread] core/setup_utils.o
[thread 3][gcc -pthread] core/clock.o
[thread 1][gcc -pthread] core/init.o
[thread 0][gcc -pthread] core/buffer.o
[thread 3][gcc -pthread] core/reader.o
[thread 2][gcc -pthread] core/writer.o
[thread 1][gcc -pthread] core/alarm.o
[thread 0][gcc -pthread] core/cron.o
[thread 3][gcc -pthread] core/hooks.o
[thread 2][gcc -pthread] core/plugins.o
[thread 1][gcc -pthread] core/lock.o
[thread 0][gcc -pthread] core/cache.o
[thread 3][gcc -pthread] core/daemons.o
[thread 2][gcc -pthread] core/errors.o
[thread 1][gcc -pthread] core/hash.o
[thread 2][gcc -pthread] core/master_events.o
[thread 1][gcc -pthread] core/chunked.o
[thread 3][gcc -pthread] core/queue.o
[thread 2][gcc -pthread] core/event.o
[thread 1][gcc -pthread] core/signal.o
[thread 0][gcc -pthread] core/strings.o
[thread 3][gcc -pthread] core/progress.o
[thread 3][gcc -pthread] core/timebomb.o
[thread 2][gcc -pthread] core/ini.o
[thread 1][gcc -pthread] core/fsmon.o
[thread 0][gcc -pthread] core/mount.o
[thread 3][gcc -pthread] core/metrics.o
[thread 2][gcc -pthread] core/plugins_builder.o
[thread 1][gcc -pthread] core/sharedarea.o
[thread 0][gcc -pthread] core/rpc.o
[thread 2][gcc -pthread] core/gateway.o
[thread 0][gcc -pthread] core/loop.o
[thread 1][gcc -pthread] core/cookie.o
[thread 2][gcc -pthread] core/querystring.o
[thread 3][gcc -pthread] core/rb_timers.o
[thread 0][gcc -pthread] core/transformations.o
[thread 1][gcc -pthread] core/uwsgi.o
[thread 2][gcc -pthread] proto/base.o
[thread 3][gcc -pthread] proto/uwsgi.o
[thread 0][gcc -pthread] proto/http.o
[thread 3][gcc -pthread] proto/fastcgi.o
[thread 2][gcc -pthread] proto/scgi.o
[thread 2][gcc -pthread] proto/puwsgi.o
[thread 3][gcc -pthread] lib/linux_ns.o
[thread 0][gcc -pthread] core/zlib.o
[thread 2][gcc -pthread] core/regexp.o
[thread 0][gcc -pthread] core/routing.o
[thread 3][gcc -pthread] core/yaml.o
[thread 2][gcc -pthread] core/ssl.o
[thread 3][gcc -pthread] core/legion.o
Traceback (most recent call last):
  File "uwsgiconfig.py", line 463, in build_uwsgi
    execfile('%s/uwsgiplugin.py' % path, up)
NameError: name 'execfile' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uwsgiconfig.py", line 1622, in <module>
    build_uwsgi(uc, is_cflags, gcll=gcll)
  File "uwsgiconfig.py", line 466, in build_uwsgi
    exec(f.read(), up)
  File "<string>", line 20, in <module>
AttributeError: 'NoneType' object has no attribute 'split'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1

```

**Comment by xrmx** [comment]
What uwsgi version are you trying to compile?

**Comment by owen800q** [comment]
> What uwsgi version are you trying to compile? And which python version too please.

uwsgi version : 2.0.18
pypy2.7 with python3.6 implementation.
It's tested under virtualenv, pypy dynamic link to python executable.
So look like this problem was caused by PyPy, I tried to built from source with Cpython. It works

**Comment by xrmx** [comment]
Am not sure "pypy2.7 with python3.6 implementation." is a version is it pypy or pypy3 and which version? Anyway it looks it is missing exec or execfile.

**Comment by owen800q** [comment]
> Am not sure "pypy2.7 with python3.6 implementation." is it a version of pypy or pypy3 and which version? Anyway it looks it is missing exec or execfile.

It's pypy3 not pypy2.7.

**Comment by owen800q** [comment]
![image](https://user-images.githubusercontent.com/19252045/65256738-98ce1080-db32-11e9-9247-7f57b234f279.png)

**Comment by awelzel** [comment]
I seems the first Exception trace is somewhat misleading - there is actually a fallback to use `exec(f.read(), up)` in place and that is run.

The `AttributeError: 'NoneType' object has no attribute 'split'` is the actual error. That appears to happens when `plugins/python/uwsgiplugin.py` is executed with pypy3:
```
$ pypy3 plugins/python/uwsgiplugin.py
Traceback (most recent call last):
  File "plugins/python/uwsgiplugin.py", line 40, in <module>
    LIBS = sysconfig.get_config_var('LIBS').split() + sysconfig.get_config_var('SYSLIBS').split()
AttributeError: 'NoneType' object has no attribute 'split'
```
Could be nicer, but hmm..

@owen800q - given you're running with pypy3 - maybe you actually want to include the pypy plugin via `python uwsgiconfig.py --build buildconf/pypy.ini`?
