### ISSUE TITLE
Werkzeug new release v1.0.0 has breaking changes

### ISSUE THREAD

**Issue by Haythamamin** [unbit/uwsgi#2124]
When installing uwsgi v2.0.18 with Werkzeug I get the following error:

```
ImportError: cannot import name 'MultiDict' from 'werkzeug' (/usr/local/lib/python3.7/site-packages/werkzeug/__init__.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
mounting wsgi.py on /app0
Traceback (most recent call last):
  File "wsgi.py", line 1, in <module>
    from server import app
  File "./server.py", line 1, in <module>
    from eve import Eve
  File "/usr/local/lib/python3.7/site-packages/eve/__init__.py", line 89, in <module>
    from eve.flaskapp import Eve  # noqa
  File "/usr/local/lib/python3.7/site-packages/eve/flaskapp.py", line 25, in <module>
    from eve.endpoints import (
  File "/usr/local/lib/python3.7/site-packages/eve/endpoints.py", line 20, in <module>
    from eve.methods import get, getitem, post, patch, delete, deleteitem, put
  File "/usr/local/lib/python3.7/site-packages/eve/methods/__init__.py", line 14, in <module>
    from eve.methods.get import get, getitem
  File "/usr/local/lib/python3.7/site-packages/eve/methods/get.py", line 18, in <module>
    from werkzeug import MultiDict
ImportError: cannot import name 'MultiDict' from 'werkzeug' (/usr/local/lib/python3.7/site-packages/werkzeug/__init__.py)
```

Workaround: Lock Werkzeug==0.16.1 that's the last known working version.

**Comment by awelzel** [comment]
@Haythamamin - this has nothing to do with `uwsgi`, it's a change in Werkzeug.

Also, the better fix is probably to upgrade to a more recent eve version once it exists:

https://github.com/pyeve/eve/issues/1359

 Please close - thanks!
