### ISSUE TITLE
Unable to mount Paste application 

### ISSUE THREAD

**Issue by codepainters** [unbit/uwsgi#2172]
1) First of all it is unclear that mount option accepts the `.ini`, like e.g. `--mount /app=config:myapp.ini`

2) It seems that `--mount` requires full absolute path to `.ini` file, otherwise `Paste-Deploy` complaints:

```python
mounting config:production.ini on /app
Loading paste environment: config:production.ini
Traceback (most recent call last):
  File "/home/czajnik/kp/webtier/superadmin/env/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/czajnik/kp/webtier/superadmin/env/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 275, in loadobj
    context = loadcontext(
  File "/home/czajnik/kp/webtier/superadmin/env/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 299, in loadcontext
    return _loaders[scheme](
  File "/home/czajnik/kp/webtier/superadmin/env/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 312, in _loadconfig
    raise ValueError(
ValueError: Cannot resolve relative uri 'config:production.ini'; no relative_to keyword argument given

```

3. When I give full path to `.ini` file, it loads OK, but the application appears at `/`, and not at the desired mount point!

```
*** Operational MODE: single process ***
uwsgi socket 0 bound to TCP address 0.0.0.0:8899 fd 3
...
mounting config:/tmp/production.ini on /app
Loading paste environment: config:/tmp/production.ini
WSGI app 0 (mountpoint='/app') ready in 1 seconds on interpreter 0x55b3de4af380 pid: 160361 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 160361, cores: 1)
```

Test requests:
```
[pid: 160361|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 793 bytes} [Mon Jun  1 12:56:10 2020] GET /app/ => generated 526 bytes in 11 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
[pid: 160361|app: 0|req: 2/2] 127.0.0.1 () {42 vars in 785 bytes} [Mon Jun  1 12:56:15 2020] GET / => generated 2973 bytes in 35 msecs (HTTP/1.1 200) 3 headers in 111 bytes (1 switches on core 0)
```

**Comment by codepainters** [comment]
OK, last point was my fault - missing `--manage-script-name`. 

Still, it seems that whichever application is mounted first, it also appears at `/`, which I consider unexpected and potentially dangerous.

**Comment by codepainters** [comment]
One more comment regarding point 2, the behavior is inconsistent:
* `--mount`  requires full path to the `.ini` file
* `--ini-paste` and `--ini-paste-logged` are happy with relative paths

Also:
* with `--mount` I can mimic the `--ini-paste` behavior, but there is no way to get `--ini-paste-logged` equivalent.
