### ISSUE TITLE
204 No Content response fails with Unhandled object from iterator: None (0x55e092be5ea0)

### ISSUE THREAD

**Issue by nberlee** [unbit/uwsgi#2185]
Since 2.0.19 an `204 No Content`  response(without a body) fails with the error `[ERROR] Unhandled object from iterator: None (0x55e092be5ea0)`

This is probably because it is incorrectly catched by the `else` added in this commit https://github.com/unbit/uwsgi/commit/10e3f0599280e245e121ce239fcf7b6ac657e89d

This worked ok in 2.0.18,  when the response is changed to `200 OK` in 2.0.19 the response is send without an error.

**Comment by rdeioris** [comment]
@nberlee thanks a lot for reporting. I have just pushed a patch (in uwsgi-2.0 branch) for excluding None from the check.
Can you confirm it works so i can make a quick release ?

**Comment by nberlee** [comment]
Hi @rdeioris, I build it, and I can confirm `204 No Content` works now without an error. Thank you for your fast response!

**Comment by xrmx** [comment]
@nberlee any chance you can add the snippet in tests/ and add it to tests/travis.sh around line 88 please?

**Comment by nberlee** [comment]
I would and tried. But I am unsure how to make this test fail correctly as it effectively only writes the `[ERROR]` log lines, when it does that at the header it already send, there is nothing more to do for a `204`. So failstate = successstate.

**Comment by xrmx** [comment]
test_python writes logs to a file we can add a `grep ERROR uwsgi.log && die "${bldred}>>> ERROR: some error"`

**Comment by awelzel** [comment]
Hey, sorry for the "regression". I've added a test case in #2191, but I'm not very happy about "allowing yield None":

The code that @nberlee showed isn't actually valid in regards to PEP333/3333. Yielding anything but `bytes` is not allowed. The original change will log any yield of non-bytes objects. And `yield None` isn't really special in this regard - so I'm not clear selectively ignoring it is good.

In comparison, running the shown code with gunicorn gives the following.
```
[2020-06-23 00:42:56 +0200] [12847] [ERROR] Error handling request                 
Traceback (most recent call last):                                                    
  File "/home/awelzel/projects/uwsgi/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 181, in handle_request                
    resp.write(item)                                                     
  File "/home/awelzel/projects/uwsgi/venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 328, in write
    raise TypeError('%r is not a byte' % arg)                            
TypeError: None is not a byte
```

**Comment by rdeioris** [comment]
@awelzel i agree with you, but as a rule we do not change behaviours in LTS releases, so if a previous uWSGI version was able to support yielding None, we need to continue supporting it. @xrmx in 2.1 we should skip my quick-and-dirty fix.

**Comment by hvt** [comment]
Mmm, what should be yielded when `None` cannot be used anymore, but to still comply with a 204 response?

**Comment by awelzel** [comment]
@hvt , in this context `return ()` instead of `yield` is an alternative.
