### ISSUE TITLE
KeyError: 'timepart_full' Segmentation Fault

### ISSUE THREAD

**Issue by icobg** [unbit/uwsgi#2352]
Python 3.10
uWSGI 2.0.20 (64bit)
compiled with version: 11.2.0
os: Linux-5.14.11 #1 SMP

Hello, after upgrade I get this error:

Exception ignored deletion of interned string failed:
Traceback (most recent call last):
  File "/usr/lib64/python3.10/sqlite3/dbapi2.py", line 83, in register_adapters_and_converters
    register_converter("timestamp", convert_timestamp)
KeyError: 'timepart_full'
Exception ignored deletion of interned string failed:
Traceback (most recent call last):
  File "/usr/lib64/python3.10/sqlite3/dbapi2.py", line 83, in register_adapters_and_converters
!!! uWSGI process 4020 got Segmentation Fault !!!
*** backtrace of 4020 ***
shopvenv2/bin/uwsgi(uwsgi_backtrace+0x2a) [0x4705ba]
shopvenv2/bin/uwsgi(uwsgi_segfault+0x21) [0x470971]
/lib64/libc.so.6(+0x3b8b0) [0x7fa181dbd8b0]
/usr/lib64/libpython3.10.so.1.0(+0x10bad4) [0x7fa18206dad4]
/usr/lib64/libpython3.10.so.1.0(_PyObject_GC_Malloc+0x35) [0x7fa18216f015]
/usr/lib64/libpython3.10.so.1.0(PyType_GenericAlloc+0x36) [0x7fa18207b726]
/usr/lib64/libpython3.10.so.1.0(+0x2577ac) [0x7fa1821b97ac]
/usr/lib64/libpython3.10.so.1.0(+0x11c686) [0x7fa18207e686]
/usr/lib64/libpython3.10.so.1.0(_PyObject_MakeTpCall+0x88) [0x7fa18201b438]
/usr/lib64/libpython3.10.so.1.0(+0xba109) [0x7fa18201c109]
/usr/lib64/libpython3.10.so.1.0(_PyObject_CallFunction_SizeT+0xc0) [0x7fa18201c3b0]
/usr/lib64/libpython3.10.so.1.0(+0x255083) [0x7fa1821b7083]
/usr/lib64/libpython3.10.so.1.0(+0x101885) [0x7fa182063885]
/usr/lib64/libpython3.10.so.1.0(+0xba063) [0x7fa18201c063]
/usr/lib64/libpython3.10.so.1.0(_PyObject_CallMethodId+0xbe) [0x7fa18201ca4e]
/usr/lib64/libpython3.10.so.1.0(+0x1f9906) [0x7fa18215b906]
/usr/lib64/libpython3.10.so.1.0(PyTraceBack_Print+0x1a9) [0x7fa18215ca49]
/usr/lib64/libpython3.10.so.1.0(+0x1bef00) [0x7fa182120f00]
/usr/lib64/libpython3.10.so.1.0(+0x1c0c9d) [0x7fa182122c9d]
/usr/lib64/libpython3.10.so.1.0(+0x10161a) [0x7fa18206361a]
/usr/lib64/libpython3.10.so.1.0(_PyErr_WriteUnraisableMsg+0x222) [0x7fa182122f52]
/usr/lib64/libpython3.10.so.1.0(+0x12af4e) [0x7fa18208cf4e]
/usr/lib64/libpython3.10.so.1.0(+0xf1395) [0x7fa182053395]
/usr/lib64/libpython3.10.so.1.0(_PyDict_DelItem_KnownHash+0x8e) [0x7fa182055cee]
/usr/lib64/libpython3.10.so.1.0(+0x12af08) [0x7fa18208cf08]
/usr/lib64/libpython3.10.so.1.0(+0x115ccb) [0x7fa182077ccb]
/usr/lib64/libpython3.10.so.1.0(+0xbcc65) [0x7fa18201ec65]
/usr/lib64/libpython3.10.so.1.0(+0xd9365) [0x7fa18203b365]
/usr/lib64/libpython3.10.so.1.0(+0xd98a2) [0x7fa18203b8a2]
/usr/lib64/libpython3.10.so.1.0(+0xf1ce5) [0x7fa182053ce5]
/usr/lib64/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so(+0xe64d) [0x7fa18157764d]
/usr/lib64/libpython3.10.so.1.0(+0x1019ef) [0x7fa1820639ef]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x745c) [0x7fa181fd1c3c]
/usr/lib64/libpython3.10.so.1.0(+0x1a6420) [0x7fa182108420]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x745c) [0x7fa181fd1c3c]
/usr/lib64/libpython3.10.so.1.0(PyEval_EvalCode+0xbc) [0x7fa18210824c]
/usr/lib64/libpython3.10.so.1.0(+0x1a0aed) [0x7fa182102aed]
/usr/lib64/libpython3.10.so.1.0(+0x1019ef) [0x7fa1820639ef]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x1640) [0x7fa181fcbe20]
/usr/lib64/libpython3.10.so.1.0(+0x1a6420) [0x7fa182108420]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x7b56) [0x7fa181fd2336]
/usr/lib64/libpython3.10.so.1.0(+0x1a6420) [0x7fa182108420]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x7294) [0x7fa181fd1a74]
/usr/lib64/libpython3.10.so.1.0(+0x1a6420) [0x7fa182108420]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x745c) [0x7fa181fd1c3c]
/usr/lib64/libpython3.10.so.1.0(+0x1a6420) [0x7fa182108420]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x745c) [0x7fa181fd1c3c]
/usr/lib64/libpython3.10.so.1.0(+0x1a6420) [0x7fa182108420]
/usr/lib64/libpython3.10.so.1.0(+0xb9b34) [0x7fa18201bb34]
/usr/lib64/libpython3.10.so.1.0(_PyObject_CallMethodIdObjArgs+0xf8) [0x7fa18201be98]
/usr/lib64/libpython3.10.so.1.0(PyImport_ImportModuleLevelObject+0x4aa) [0x7fa1821314da]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x9722) [0x7fa181fd3f02]
/usr/lib64/libpython3.10.so.1.0(PyEval_EvalCode+0xbc) [0x7fa18210824c]
/usr/lib64/libpython3.10.so.1.0(+0x1a0aed) [0x7fa182102aed]
/usr/lib64/libpython3.10.so.1.0(+0x1019ef) [0x7fa1820639ef]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x1640) [0x7fa181fcbe20]
/usr/lib64/libpython3.10.so.1.0(+0x1a6420) [0x7fa182108420]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x7b56) [0x7fa181fd2336]
/usr/lib64/libpython3.10.so.1.0(+0x1a6420) [0x7fa182108420]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x7294) [0x7fa181fd1a74]
/usr/lib64/libpython3.10.so.1.0(+0x1a6420) [0x7fa182108420]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x745c) [0x7fa181fd1c3c]
/usr/lib64/libpython3.10.so.1.0(+0x1a6420) [0x7fa182108420]
/usr/lib64/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x745c) [0x7fa181fd1c3c]
*** end of backtrace ***

**Comment by uckelman** [comment]
It looks like this Python bug: https://bugs.python.org/issue46070
