### ISSUE TITLE
Got segmentation fault from py_uwsgi_gevent_request

### ISSUE THREAD

**Issue by gavin-jeong** [unbit/uwsgi#2457]
Some environment info.
This happens only on python3 with websocket, not on python2.
It been reproduced on 2.0.20 as well.

```bash
$ python --version
Python 3.8.13
$ uwsgi --version
2.0.19.1
$ uname -srvmpio
Linux 5.13.0-1031-aws #35~20.04.1-Ubuntu SMP Mon Jun 13 22:33:23 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

Stack trace
```bash
$ coredumpctl debug
...
(gdb) bt
#0  0x0000ffff9e69f9b0 in ?? () from /lib/aarch64-linux-gnu/libgcc_s.so.1
#1  0x0000ffff9e6a1100 in _Unwind_Backtrace () from /lib/aarch64-linux-gnu/libgcc_s.so.1
#2  0x0000ffffa067ddbc in __GI___backtrace (array=<optimized out>, size=<optimized out>) at backtrace.c:116
#3  0x0000aaaaac05f38c in uwsgi_backtrace ()
#4  0x0000aaaaac05f754 in uwsgi_segfault ()
#5  <signal handler called>
#6  0x0000aaaaac089368 in py_uwsgi_gevent_request ()
#7  0x0000ffffa07dd534 in cfunction_call_varargs (kwargs=<optimized out>, args=0xffff628d97f0, func=0xffff629370e0) at Objects/call.c:758
#8  PyCFunction_Call (func=0xffff629370e0, args=0xffff628d97f0, kwargs=<optimized out>) at Objects/call.c:773
#9  0x0000ffff9dd3cf40 in __Pyx_PyObject_Call (kw=0xffff62921bc0, arg=0xffff628d97f0, func=0xffff629370e0) at src/gevent/greenlet.c:25420
#10 __pyx_pf_6gevent_17_gevent_cgreenlet_8Greenlet_42run (__pyx_v_self=0xffff628c4260) at src/gevent/greenlet.c:14310
#11 __pyx_pw_6gevent_17_gevent_cgreenlet_8Greenlet_43run (__pyx_v_self=0xffff628c4260, unused=<optimized out>) at src/gevent/greenlet.c:14213
#12 0x0000ffff9dd1f8ac in __Pyx_CyFunction_Vectorcall_NOARGS (func=<optimized out>, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ./src/gevent/_generated_include/CythonFunctionShared_impl_b8d451d411168c5bfd24309f8017c779ed1ebdda.h:552
#13 0x0000ffffa07df994 in _PyObject_Vectorcall (kwnames=0x0, nargsf=1, args=0xffffd5c19ce8, callable=0xffff9ddcb790) at ./Include/cpython/abstract.h:127
#14 method_vectorcall (method=method@entry=0xffff6291ccc0, args=0xffff9e2e8058, nargsf=nargsf@entry=0, kwnames=0x0) at Objects/classobject.c:67
#15 0x0000ffffa07ddbb4 in PyVectorcall_Call (callable=0xffff6291ccc0, tuple=<optimized out>, kwargs=<optimized out>) at Objects/call.c:200
#16 0x0000ffff9df2e894 in g_initialstub (mark=mark@entry=0xffffd5c19e38) at src/greenlet/greenlet.c:875
#17 0x0000ffff9df2eb30 in g_switch (kwargs=<optimized out>, args=<optimized out>, target=0xffff628c4260) at src/greenlet/greenlet.c:652
#18 g_switch (target=<optimized out>, args=0xffff9e2e8040, kwargs=<optimized out>) at src/greenlet/greenlet.c:614
#19 0x0000ffff9df2f05c in green_switch (self=<optimized out>, args=<optimized out>, kwargs=<optimized out>) at src/greenlet/greenlet.c:1204
#20 0x61cf9b7e32f7a800 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Check the line
```bash
(gdb) info line *(0x0000aaaaac089368)
No line number information available for address 0xaaaaac089368 <py_uwsgi_gevent_request+216>
(gdb) x/ni 0x0000aaaaac089368
   0xaaaaac089368 <py_uwsgi_gevent_request+216>:        ldr     x1, [x0]
```

And found it from objdump
```bash
$ objdump -d $(which uwsgi)
...
00000000000b9290 <py_uwsgi_gevent_request>:
...
   b9364:       97ffb95d        bl      a78d8 <python_call>
>  b9368:       f9400001        ldr     x1, [x0]
   b936c:       d1000421        sub     x1, x1, #0x1
   b9370:       f9000001        str     x1, [x0]
   b9374:       b5fffda1        cbnz    x1, b9328 <py_uwsgi_gevent_request+0x98>
   b9378:       97fe09b2        bl      3ba40 <_Py_Dealloc@plt>
...
```

And seems the above is related to GEVENT_SWITCH https://github.com/unbit/uwsgi/blob/master/plugins/gevent/gevent.c#L326
```c
	for(;;) {
		if (uwsgi.p[wsgi_req->uh->modifier1]->request(wsgi_req) <= UWSGI_OK) {
			goto end;
		}
		wsgi_req->switches++;
		// switch after each yield
		GEVENT_SWITCH;
	}
```
which defined here https://github.com/unbit/uwsgi/blob/master/plugins/gevent/gevent.h#L7
```c
#define GEVENT_SWITCH PyObject *gswitch = python_call(ugevent.greenlet_switch, ugevent.greenlet_switch_args, 0, NULL); Py_DECREF(gswitch)
```

It looks a little dangerous that it doesn't check the gswitch address.
Not sure why this happens only on python3 with websocket environment, anyway it would be better add a null check.

**Comment by gavin-jeong** [comment]
Rebuild with debug option.
Confirmed that nil value is assigned to the gswitch.

```bash
#6  _Py_DECREF (filename=<synthetic pointer>, lineno=320, op=0x0) at /usr/local/include/python3.8/object.h:470
No locals.
#7  py_uwsgi_gevent_request (self=<optimized out>, args=<optimized out>) at plugins/gevent/gevent.c:320
        gswitch = 0x0
        py_wsgi_req = <optimized out>
        wsgi_req = 0xffff9aa9c6d8
        greenlet_switch = <optimized out>
        current_greenlet = 0xffff501066a0
```
