### ISSUE TITLE
Not compatible with python 3.12

### ISSUE THREAD

**Issue by cheikh1111** [unbit/uwsgi#2618]
# im using python 3.12 and i updated pip and setup tools by pip3 install --upgrade pip setuptools but i get this problem:

Collecting uwsgi==2.0
  Using cached uwsgi-2.0.tar.gz (744 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\cheikh\Desktop\Developer\Voting\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\cheikh\Desktop\Developer\Voting\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\cheikh\Desktop\Developer\Voting\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\cheikh\AppData\Local\Temp\pip-build-env-fqal3ig5\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel      
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\cheikh\AppData\Local\Temp\pip-build-env-fqal3ig5\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\cheikh\AppData\Local\Temp\pip-build-env-fqal3ig5\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\cheikh\AppData\Local\Temp\pip-build-env-fqal3ig5\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "C:\Users\cheikh\AppData\Local\Temp\pip-install-6bp7cd__\uwsgi_e7ecb68e7cc44be19088d3709f83323a\uwsgiconfig.py", line 8, in <module>
          uwsgi_os = os.uname()[0]
                     ^^^^^^^^
      AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

# Please fix it soon

**Comment by markkuleinio** [comment]
https://docs.python.org/3/library/os.html#os.uname:

> [Availability](https://docs.python.org/3/library/intro.html#availability): Unix.
