### ISSUE TITLE
Installation help on WINDOWS8

### ISSUE THREAD

**Issue by bhaskarsai** [unbit/uwsgi#547]
I have been using pip install uwsgi and easy_install uwsgi and they both threw the following error.  I understand that my version of python doesn't have os.name which is causing the fire.

This is my last of installation to the next level setup.  help me how to handle this and install properly on my virtualenv.

Thanks 

---

C:\works\python_virt\adl_lrs\env\Scripts\pip-script.py run on 02/22/14 09:01:37
Downloading/unpacking http://projects.unbit.it/downloads/uwsgi-lts.tar.gz

  Downloading from URL http://projects.unbit.it/downloads/uwsgi-lts.tar.gz
  Running setup.py egg_info for package from http://projects.unbit.it/downloads/uwsgi-lts.tar.gz

```
Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "c:\users\bhaskra\appdata\local\temp\pip-q_mapi-build\setup.py", line 3, in <module>

    import uwsgiconfig as uc

  File "uwsgiconfig.py", line 8, in <module>

    uwsgi_os = os.uname()[0]

AttributeError: 'module' object has no attribute 'uname'

Complete output from command python setup.py egg_info:

Traceback (most recent call last):
```

  File "<string>", line 16, in <module>

  File "c:\users\bhaskra\appdata\local\temp\pip-q_mapi-build\setup.py", line 3, in <module>

```
import uwsgiconfig as uc
```

  File "uwsgiconfig.py", line 8, in <module>

```
uwsgi_os = os.uname()[0]
```

AttributeError: 'module' object has no attribute 'uname'

---

Command python setup.py egg_info failed with error code 1 in c:\users\bhaskra\appdata\local\temp\pip-q_mapi-build

Exception information:
Traceback (most recent call last):
  File "C:\works\python_virt\adl_lrs\env\lib\site-packages\pip-1.3.1-py2.7.egg\pip\basecommand.py", line 139, in main
    status = self.run(options, args)
  File "C:\works\python_virt\adl_lrs\env\lib\site-packages\pip-1.3.1-py2.7.egg\pip\commands\install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\works\python_virt\adl_lrs\env\lib\site-packages\pip-1.3.1-py2.7.egg\pip\req.py", line 1057, in prepare_files
    req_to_install.run_egg_info()
  File "C:\works\python_virt\adl_lrs\env\lib\site-packages\pip-1.3.1-py2.7.egg\pip\req.py", line 236, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\works\python_virt\adl_lrs\env\lib\site-packages\pip-1.3.1-py2.7.egg\pip\util.py", line 662, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in c:\users\bhaskra\appdata\local\temp\pip-q_mapi-build

**Comment by winman826** [comment]
Hello, How are you?
as you mentioned above, Can't I install uwsgi on windows in any ways?
In django book, tells that can install it by using cygwin.
So, please let me know your way.
Regards.

**Comment by adam993** [comment]
wow this is a disappointment... Going to switch to linux soon though, but anyways it would be good to fix this

**Comment by unbit** [comment]
@adam993 the linux layer in windows 10 works without problems. From my point of view it is a better solution than using cygwin
