### ISSUE TITLE
uwsgi_file_app_wsgi.__spec__ is None with python 3.4

### ISSUE THREAD

**Issue by gdamjan** [unbit/uwsgi#621]
Running the Flask hello world app fails with this exception

```
Python version: 3.4.0 (default, Apr 27 2014, 23:33:09)  [GCC 4.8.2 20140206 (prerelease)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2600610
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
uwsgi_file_app_wsgi
Traceback (most recent call last):
  File "/usr/lib/python3.4/pkgutil.py", line 481, in find_loader
    spec = importlib.util.find_spec(fullname)
  File "/usr/lib/python3.4/importlib/util.py", line 100, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: uwsgi_file_app_wsgi.__spec__ is None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.wsgi", line 6, in <module>
    app = Flask(__name__)
  File "/home/damjan/X/py-env/lib/python3.4/site-packages/flask/app.py", line 331, in __init__
    instance_path = self.auto_find_instance_path()
  File "/home/damjan/X/py-env/lib/python3.4/site-packages/flask/app.py", line 622, in auto_find_instance_path
    prefix, package_path = find_package(self.import_name)
  File "/home/damjan/X/py-env/lib/python3.4/site-packages/flask/helpers.py", line 661, in find_package
    loader = pkgutil.get_loader(root_mod_name)
  File "/usr/lib/python3.4/pkgutil.py", line 467, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python3.4/pkgutil.py", line 487, in find_loader
    raise ImportError(msg.format(fullname, type(ex), ex)) from ex
ImportError: Error while finding loader for 'uwsgi_file_app_wsgi' (<class 'ValueError'>: uwsgi_file_app_wsgi.__spec__ is None)
unable to load app 0 (mountpoint='') (callable not found or import error)
```

The command line is: uwsgi --plugin python --env PYTHONUSERBASE=$PWD/py-env --wsgi-file app.wsgi --http-socket :8000 --master

The app.wsgi is the Flask hello world, with the following change:

```
if __name__ == "__main__":
    app.run()
else:
    application = app
```

**Comment by joelwhitehouse** [comment]
I'm on ubuntu trusty with the same error message.  I'm also trying to run flask from python3 and serve with uwsgi.

`uwsgi --version` 1.9.17.1-debian
`apt-cache showpkg uwsgi-plugin-python3` Versions: 1.9.17.1-5build5
`python3 --version` Python 3.4.0
`apt-cache showpkg python3-flask` Versions: 0.10.1-2build1

My parameters are set from an ini file:
```ini
[uwsgi]
plugins = python3
socket = :8000
process   = 1
chdir =  /var/www/html
file = myapp.py
callable = app
uid = www-data
gid = www-data
```
And my flask applications was:
```python
from flask import Flask
app = Flask(__name__)
@app.route('/')
def hello_world():
    return 'Hello World!'
if __name__ == '__main__':
    app.run()
```

@unbit I'm not sure what you mean by 
> If you use a wsgi module instead of a file all works as expected.

How could I go about converting this from a file-based app to a wsgi module?

**Comment by unbit** [comment]
just add the dir containing the file to the pythonpath with

```ini
pythonpath = <path>
```

then

```ini
; without .py suffix !
module = myapp
```

**Comment by joelwhitehouse** [comment]
I have changed my config to:
```ini
[uwsgi]
plugins = python3
socket = :8000 
process   = 1
chdir =  /var/www/html
callable = app
pythonpath = /var/www/html
module = myapp
uid = www-data
gid = www-data
```
@unbit, it works, thank you!!!

**Comment by tomkcook** [comment]
This works for me; however, when I try to use a mountpoint, I get the error shown above.  My uwsgi.ini:

    [uwsgi]
    plugin = python3
    socket = /tmp/myapp.sock
    chdir = /home/me/myapp/src
    venv = /home/me/myapp/venv
    mount = /myapp=myapp.py
    callable = app
    manage-script-name = true

Removing the `.py` from the end of the mount command results in the 'no python application found...' message.

Is there a way to use mountpoints with python 3?

**Comment by JonasGroeger** [comment]
Very same issue here.

```
$ sudo uwsgi --plugin=python3 --socket=/tmp/brieffenster.sock --chown-socket=www-data:www-data --chdir=/var/www/projekte/brieffenster --virtualenv=/var/www/projekte/brieffenster/.env --mount=/=brieffenster.py --callable=app --manage-script-name --pythonpath=/var/www/projekte/brieffenster/
*** Starting uWSGI 1.9.17.1-debian (64bit) on [Tue Aug 18 23:00:27 2015] ***
compiled with version: 4.8.2 on 23 March 2014 17:15:32
os: Linux-2.6.32-042stab094.7 #1 SMP Wed Oct 22 12:43:21 MSK 2014
nodename: bender
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/fry/brieffenster
detected binary path: /usr/bin/uwsgi-core
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 514091
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/brieffenster.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.4.0 (default, Jun 19 2015, 14:24:19)  [GCC 4.8.2]
Set PythonHome to /var/www/projekte/brieffenster/.env
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x12afa20
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72792 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
added /var/www/projekte/brieffenster/ to pythonpath.
mounting brieffenster.py on /
Traceback (most recent call last):
  File "/usr/lib/python3.4/pkgutil.py", line 481, in find_loader
    spec = importlib.util.find_spec(fullname)
  File "/var/www/projekte/brieffenster/.env/lib/python3.4/importlib/util.py", line 100, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: uwsgi_file_brieffenster.__spec__ is None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "brieffenster.py", line 10, in <module>
    app = Flask(__name__)
  File "/var/www/projekte/brieffenster/.env/lib/python3.4/site-packages/flask/app.py", line 331, in __init__
    instance_path = self.auto_find_instance_path()
  File "/var/www/projekte/brieffenster/.env/lib/python3.4/site-packages/flask/app.py", line 622, in auto_find_instance_path
    prefix, package_path = find_package(self.import_name)
  File "/var/www/projekte/brieffenster/.env/lib/python3.4/site-packages/flask/helpers.py", line 661, in find_package
    loader = pkgutil.get_loader(root_mod_name)
  File "/usr/lib/python3.4/pkgutil.py", line 467, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python3.4/pkgutil.py", line 487, in find_loader
    raise ImportError(msg.format(fullname, type(ex), ex)) from ex
ImportError: Error while finding loader for 'uwsgi_file_brieffenster' (<class 'ValueError'>: uwsgi_file_brieffenster.__spec__ is None)
```

**Comment by unbit** [comment]
Try this syntax:

--mount <path>=<module>:<callable>

Something like

--mount /foobar=myapp:app

**Comment by JonasGroeger** [comment]
@unbit This made it work! Thanks so much!

```
mount = /projekte/brieffenster=brieffenster:app
manage-script-name = true
# callable = app <- You can remove this
```
