### ISSUE TITLE
cron error

### ISSUE THREAD

**Issue by xurwxj** [unbit/uwsgi#836]
Internal Server Error: /inquiry/list/
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
   resolver_match = resolver.resolve(request.path_info)
 File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 345, in resolve
   sub_match = pattern.resolve(new_path)
 File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 345, in resolve
   sub_match = pattern.resolve(new_path)
 File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 345, in resolve
   sub_match = pattern.resolve(new_path)
 File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
   return ResolverMatch(self.callback, args, kwargs, self.name)
 File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
   self._callback = get_callable(self._callback_str)
 File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
   result = user_function(*args, **kwds)
 File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
   mod = import_module(mod_name)
 File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
   __import__(name)
 File "/home/ys/market/libs/inquiry/views.py", line 30, in <module>
   from market.task import matching_inquiry_task
 File "/home/ys/market/task.py", line 39, in <module>
   @cron(20, 2, -1, -1, -1)
 File "/usr/local/lib/python2.7/dist-packages/uwsgidecorators.py", line 334, in __call__
   self.day, self.month, self.dayweek)
ValueError: unable to add cron

@cron(20, 2, -1, -1, -1)
def recycle_inquiry_cron(arg):
    """ 回收询盘 """
    from django.core import management
    import uwsgi

    resp = management.call_command('recycle_inquiry', verbosity=0)

    if resp:
        return uwsgi.SPOOL_RETRY
    return uwsgi.SPOOL_OK

what's wrong for us?tks.

**Comment by xurwxj** [comment]
total 4 cron under project for seprated app, 3 others is ok except this one.

uwsgi: 2.0.9
python: 2.7
os: ubuntu 14.10

**Comment by unbit** [comment]
Sorry, the markdown parser has "broken" your request, can you reformat it ? Thanks

**Comment by xrmx** [comment]
No user response since months. The code looks like a cron that return spooler status so some clue of code issues. Closing.
