### ISSUE TITLE
uWSGI + PyPy - "You have to enable the uWSGI master process to use this module"

### ISSUE THREAD

**Issue by zoomorph** [unbit/uwsgi#842]
I'm attempting to migrate a working uWSGI + Python app to uWSGI + PyPy.

uWSGI - 2.0.9
PyPy - a nightly build from last week

command line:
`/myapp/env_pypy/bin/uwsgi -s /tmp/uwsgi.sock --pypy-wsgi webserver:tpapp --ini uwsgi.ini`

INI file:
```
[uwsgi]
master = true
pidfile = master.pid
workers = 3
chdir = /myapp/bin
socket = /myapp/uwsgi.sock
chmod-socket = 666
harakiri = 30
harakiri-verbose = True
max-requests = 100000
vacuum = True
enable-threads = True
strict = True
stats = /myapp/stats.sock
cache2 = name=usercache,items=100,purge_lru=1
queue = 8
locks = 8
```

Here's the error I receive:
```
*** Operational MODE: preforking ***
Verifying path: /var/log/tp
Verifying path: /myapp/tpweb/data
Verifying path: /myapp/tpweb/data/modules
Verifying path: /myapp/tpweb/data/sessions
From cffi callback <function uwsgi_pypy_loader at 0x0aa8a950>:
Traceback (most recent call last):
  File "c callback", line 303, in uwsgi_pypy_loader
  File "./webserver.py", line 20, in <module>
    from myapp.versioning import initialize_file_monitors, update_static_files
  File "/myapp/tpweb/versioning.py", line 10, in <module>
    from uwsgidecorators import lock
  File "/myapp/env_pypy/site-packages/uwsgidecorators.py", line 14, in <module>
    "you have to enable the uWSGI master process to use this module")
Exception: you have to enable the uWSGI master process to use this module
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
```

Is master=true not sufficient to enable the master process?

**Comment by unbit** [comment]
The pypy plugin (currently) does not expose enough api functions to work with the uwsgidecorators module. In this specific case the uwsgi.opt dictionary is not available

**Comment by zoomorph** [comment]
Ah, OK, thanks unbit. Sticking with Python for now I guess.

**Comment by xrmx** [comment]
Question has been answered, closing this.
