### ISSUE TITLE
gevent error: cannot switch to a different thread

### ISSUE THREAD

**Issue by dmk23** [unbit/uwsgi#887]
We deployed a Django app to uWSGI / gevent under a moderate load. The wsgi module (wrapper around Django's) did the full monkey patching as the first line with ```monkey.patch_all()```. Surprisingly we have encountered the following error lines in the log : 

```
Traceback (most recent call last):	
Traceback (most recent call last):	
  File "_semaphore.py", line 50, in gevent._semaphore.Semaphore._notify_links (gevent/gevent._semaphore.c:1735)	
  File "/opt/venv/lib/python2.7/site-packages/django/dispatch/saferef.py", line 121, in remove	
    function( self )	
  File "/opt/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 270, in _remove_receiver	
error: cannot switch to a different thread	
(<built-in method switch of greenlet.greenlet object at 0x7ffb0045d370>,	
 <gevent._semaphore.Semaphore object at 0x7ffb0ff62b10>) failed with error	
	
    with self.lock:	
  File "_semaphore.py", line 128, in gevent._semaphore.Semaphore.__enter__ (gevent/gevent._semaphore.c:3574)	
  File "_semaphore.py", line 112, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:3122)	
  File "/opt/venv/lib/python2.7/site-packages/gevent/hub.py", line 345, in switch	
    return greenlet.switch(self)	
LoopExit: This operation would block forever
```

Since none of the traceback lines refer to our app we'd have to assume that the problem may be somewhere in the container. Is there anything in uWSGI and/or Gevent implementation that might be causing / associated with this behavior? Could it potentially cause other problems?

**Comment by unbit** [comment]
Can you paste your uWSGI config ? it looks like you have combined some form of multithreading with greenlets (and this is forbidden). Paste the wsgi.py too (just for being sure)

**Comment by dmk23** [comment]
We've only enabled threads, not tried to create native ones (with ```threads = x```) -

uwsgi.ini : 
```
http-socket = 0.0.0.0:$(PORT)
stats = 0.0.0.0:$(STATUS_PORT)
listen = 1000

virtualenv = $(VIRTUALENV)
wsgi-file = wsgi.py
env = DJANGO_SETTINGS_MODULE=$(DJANGO_SETTINGS_MODULE)

master = True
vacuum = True
die-on-term = True
no-orphans = True
single-interpreter = True
strict = True

processes = 20
enable-threads = True
gevent = 100
max-fd = 100000
thunder-lock = serialize accept() usage

cheaper-algo = busyness
cheaper-overload = 90
cheaper-busyness-max = 80
cheaper = 4
cheaper-initial = 4
cheaper-step = 2
```

wsgi.py
```
from gevent import monkey
monkey.patch_all()
print "wsgi.py: Monkey-patched Gevent"

import os
import importlib
importlib.import_module(os.environ['DJANGO_SETTINGS_MODULE'])
print "wsgi.py: Imported settings"

from django.conf import settings
from django.db.backends.mysql import base
from sqlalchemy import pool
settings.DATABASES['default']['OPTIONS']['sa_pool_key'] = "default" # SQLalchemy pool fix
base.Database = pool.manage(base.Database, recycle=3600, echo=True, reset_on_return=False)
print "wsgi.py: Configured DB connection pooling"

### here go the imports for our proprietary app modules ###

import uwsgi
from django.core.handlers.wsgi import WSGIHandler as DjangoHandler

class WSGIHandler(DjangoHandler):
    def __call__(self, environ, start_response):
        # placeholder for future modifications
        response = super(WSGIHandler, self).__call__(environ, start_response)
        return response

application = WSGIHandler()
print "wsgi.py: Initialized WSGI Handler"
```
