### ISSUE TITLE
why my python3.4 install uwsgi error

### ISSUE THREAD

**Issue by wakaryry** [unbit/uwsgi#970]
``` cmd
C:\Users\Administrator>d:/python34/scripts/pip.exe install uwsgi
You are using pip version 6.0.8, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting uwsgi
  Using cached uwsgi-2.0.11.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-mo5ohn0i\uwsgi\setup.
py", line 3, in <module>
        import uwsgiconfig as uc
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-mo5ohn0i\uwsgi\uwsgic
onfig.py", line 8, in <module>
        uwsgi_os = os.uname()[0]
    AttributeError: 'module' object has no attribute 'uname'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-mo5ohn0i\uwsgi\setup.
py", line 3, in <module>

        import uwsgiconfig as uc

      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-mo5ohn0i\uwsgi\uwsgic
onfig.py", line 8, in <module>

        uwsgi_os = os.uname()[0]

    AttributeError: 'module' object has no attribute 'uname'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMI
NI~1\AppData\Local\Temp\pip-build-mo5ohn0i\uwsgi

```

**Comment by unbit** [comment]
uWSGI requires a UNIX environment. Windows is supported only via cygwin

**Comment by wakaryry** [comment]
Got it. Thanks.
